/* =========================================================
   AN Rus Dili Platforması — Dərs Məlumatları
   CHILD_LEVELS: 7-12 yaş proqramı (mövcud, dəyişməz saxlanıb)
   ADULT_LEVELS: Yeniyetmə/Böyük proqramı — CEFR (A1-B2) əsaslı
   ========================================================= */

const CHILD_LEVELS = [
{id:'lvl1',name:'Səviyyə 1 — Başlanğıc',lessons:[
 {id:'l1',emoji:'🔤',title:'Əlifba: А-Д',meta:'Hərflər və səslər',desc:'Rus əlifbasının ilk hərfləri: А, Б, В, Г, Д. Rəngli kartlar və səs təqlidi ilə öyrənmə.',words:['А — Аист (Leylək)','Б — Бабочка (Kəpənək)','В — Волк (Qurd)','Г — Гриб (Göbələk)','Д — Дом (Ev)'],hw:['А,Б,В,Г,Д hərflərini 5 dəfə yazın.','Hər hərflə başlayan əşyanın şəklini çəkin.'],
 quiz:[{q:'"Дом" sözü nə deməkdir?',o:['Ev','İt','Günəş'],a:0},{q:'"Волk" hansı hərflə başlayır?',o:['А','В','Д'],a:1}]},
 {id:'l2',emoji:'👋',title:'Salamlaşma',meta:'Gündəlik ifadələr',desc:'Salam, necəsən, sağ ol kimi əsas salamlaşma sözləri və rollu dialoq oyunları.',words:['Привет — Salam','Здравствуйте — Salam (hörmətlə)','Как дела? — Necəsən?','Спасибо — Sağ ol','До свидания — Sağol'],hw:['"Привет, как дела?" cümləsini 3 dəfə yazın.','Ailə üzvü ilə salamlaşma məşqi.'],
 quiz:[{q:'"Спасибо" nə deməkdir?',o:['Sağ ol','Salam','Bağışla'],a:0},{q:'"Necəsən?" rusca necə deyilir?',o:['Привет','Как дела?','До свидания'],a:1}]},
 {id:'l3',emoji:'👨‍👩‍👧‍👦',title:'Ailə üzvləri',meta:'Ailə sözləri',desc:'Ana, ata, bacı, qardaş kimi ailə üzvlərinin adları, ailə ağacı tapşırığı ilə.',words:['Мама — Ana','Папа — Ata','Брат — Qardaş','Сестра — Bacı','Бабушка — Nənə','Дедушка — Baba'],hw:['Ailənizin şəklini çəkin, hər üzvün adını rusca yazın.','"Это моя мама" cümləsini yazın.'],
 quiz:[{q:'"Брат" kim deməkdir?',o:['Bacı','Qardaş','Ata'],a:1},{q:'"Nənə" rusca necə yazılır?',o:['Дедушка','Бабушка','Мама'],a:1}]},
 {id:'l4',emoji:'🐾',title:'Heyvanlar',meta:'Heyvan adları',desc:'Ev və vəhşi heyvanların adları, heyvan səsləri təqlidi ilə əyləncəli dərs.',words:['Кошка — Pişik','Собака — İt','Лошадь — At','Медведь — Ayı','Заяц — Dovşan'],hw:['5 heyvan adını rusca yazın və şəklini çəkin.','Sevimli heyvanınızı rusca 1 cümlə ilə təsvir edin.'],
 quiz:[{q:'"Собака" deməkdir:',o:['Pişik','İt','At'],a:1},{q:'"Ayı" rusca necə yazılır?',o:['Медведь','Заяц','Кошка'],a:0}]},
 {id:'l5',emoji:'🎨',title:'Rənglər',meta:'Əsas rənglər',desc:'Qırmızı, göy, sarı, yaşıl kimi əsas rəngləri öyrənmə, rəngləmə vərəqi ilə.',words:['Красный — Qırmızı','Синий — Göy','Жёлтый — Sarı','Зелёный — Yaşıl','Белый — Ağ'],hw:['5 əşyanın rəngini rusca yazın.','Otağınızdakı rəngli əşyaları sayın.'],
 quiz:[{q:'"Жёлтый" nə rəngdir?',o:['Qırmızı','Sarı','Göy'],a:1},{q:'"Yaşıl" rusca necə yazılır?',o:['Зелёный','Белый','Синий'],a:0}]},
 {id:'l6',emoji:'🔢',title:'Rəqəmlər 1-10',meta:'Say-say oyunu',desc:'1-dən 10-a qədər rəqəmləri öyrənmə, oyuncaqlarla say-say oyunu.',words:['Один — 1','Два — 2','Три — 3','Четыре — 4','Пять — 5'],hw:['1-dən 10-a qədər rəqəmləri rusca yazın.','Otaqdaki əşyaları sayaraq rusca deyin.'],
 quiz:[{q:'"Три" hansı rəqəmdir?',o:['2','3','5'],a:1},{q:'"5" rusca necə deyilir?',o:['Четыре','Пять','Два'],a:1}]},
 {id:'l7',emoji:'🍎',title:'Yeməklər',meta:'Qida adları',desc:'Ən çox işlənən yemək adları: alma, çörək, süd, pendir və s.',words:['Яблоко — Alma','Хлеб — Çörək','Молоко — Süd','Сыр — Pendir','Вода — Su'],hw:['Sevdiyiniz 3 yeməyi rusca yazın.','"Я хочу молоко" cümləsini yazın.'],
 quiz:[{q:'"Хлеб" nə deməkdir?',o:['Çörək','Su','Alma'],a:0},{q:'"Süd" rusca necə yazılır?',o:['Сыр','Молоко','Вода'],a:1}]},
 {id:'l8',emoji:'🎵',title:'Səviyyə 1 Təkrarı',meta:'Ümumiləşdirmə + mahnı',desc:'1-ci səviyyənin bütün mövzuları mahnı və oyunla təkrarlanır, kiçik tamaşa hazırlanır.',words:['Təkrar: əlifba','Təkrar: salamlaşma','Təkrar: ailə','Təkrar: heyvanlar, rənglər, rəqəmlər'],hw:['Öyrəndiyiniz 10 sözü dəftərə yazın.','Valideynə bu həftə öyrəndiklərinizi danışın.'],
 quiz:[{q:'"Привет" + "Спасибо" — bunlar nədir?',o:['Rənglər','Salamlaşma sözləri','Heyvanlar'],a:1},{q:'Səviyyə 1-də neçə hərf öyrəndik?',o:['3','5','10'],a:1}]}
]},
{id:'lvl2',name:'Səviyyə 2 — Orta',lessons:[
 {id:'l9',emoji:'📅',title:'Həftənin günləri',meta:'Vaxt anlayışları',desc:'Həftənin günləri və "bu gün/sabah" kimi vaxt ifadələri, təqvim oyunu ilə.',words:['Понедельник — B.ertəsi','Среда — Çərşənbə','Пятница — Cümə','Сегодня — Bu gün','Завтра — Sabah'],hw:['Həftənin 7 gününü rusca yazın.','"Сегодня среда" kimi cümlə qurun.'],
 quiz:[{q:'"Пятница" hansı gündür?',o:['B.ertəsi','Cümə','Çərşənbə'],a:1},{q:'"Sabah" rusca necə deyilir?',o:['Сегодня','Завтра','Среда'],a:1}]},
 {id:'l10',emoji:'🏠',title:'Ev və otaqlar',meta:'Məkan sözləri',desc:'Ev daxilindəki otaqlar və əşyaların adları, "harada?" sualı ilə məşq.',words:['Кухня — Mətbəx','Спальня — Yataq otağı','Стол — Stol','Стул — Stul','Окно — Pəncərə'],hw:['Evinizin planını çəkin, otaqları rusca adlandırın.','"Где стол?" sualına cavab yazın.'],
 quiz:[{q:'"Кухня" deməkdir:',o:['Mətbəx','Yataq otağı','Pəncərə'],a:0},{q:'"Stul" rusca necə yazılır?',o:['Стол','Стул','Окно'],a:1}]},
 {id:'l11',emoji:'👕',title:'Geyimlər',meta:'Geyim adları',desc:'Köynək, şalvar, ayaqqabı kimi geyim adları, fəsillərə uyğun geyim oyunu.',words:['Рубашка — Köynək','Брюки — Şalvar','Туфли — Ayaqqabı','Шапка — Papaq','Куртка — Gödəkçə'],hw:['Geyindiyiniz əşyaları rusca yazın.','Qışda geyilən 3 geyim adını yazın.'],
 quiz:[{q:'"Туфли" nə deməkdir?',o:['Papaq','Ayaqqabı','Köynək'],a:1},{q:'"Gödəkçə" rusca necə yazılır?',o:['Куртка','Брюки','Рубашка'],a:0}]},
 {id:'l12',emoji:'🌦️',title:'Hava şəraiti',meta:'Təbiət hadisələri',desc:'Günəşli, yağışlı, qarlı kimi hava sözləri, fəsil şəkilləri ilə müzakirə.',words:['Солнце — Günəş','Дождь — Yağış','Снег — Qar','Ветер — Külək','Холодно — Soyuqdur'],hw:['Bu gün havanın necə olduğunu rusca yazın.','4 fəslin adını rusca öyrənin (əlavə resurslardan).'],
 quiz:[{q:'"Дождь" nə deməkdir?',o:['Qar','Yağış','Günəş'],a:1},{q:'"Soyuqdur" rusca necə deyilir?',o:['Холодно','Ветер','Солнце'],a:0}]},
 {id:'l13',emoji:'🔢',title:'Fellər: olmaq, etmək',meta:'Sadə qrammatika',desc:'"Mən edirəm", "sən edirsən" kimi sadə fel formaları, hərəkət şəkilləri ilə.',words:['Я делаю — Mən edirəm','Ты играешь — Sən oynayırsan','Он читает — O oxuyur','Мы идём — Biz gedirik'],hw:['"Я делаю..." ilə 2 cümlə qurun.','Bir hərəkəti rusca təsvir edin (məs. qaçmaq, oxumaq).'],
 quiz:[{q:'"Он читает" nə deməkdir?',o:['O oxuyur','O qaçır','O yatır'],a:0},{q:'"Biz gedirik" rusca necə yazılır?',o:['Мы идём','Ты играешь','Я делаю'],a:0}]},
 {id:'l14',emoji:'🏫',title:'Məktəb əşyaları',meta:'Dərs ləvazimatları',desc:'Kitab, dəftər, qələm kimi məktəb əşyalarının adları, çantanı doldurma oyunu.',words:['Книга — Kitab','Тетрадь — Dəftər','Карандаш — Qələm','Ручка — Qələm (tükənməz)','Сумка — Çanta'],hw:['Çantanızdaki əşyaları rusca sadalayın.','"Это моя книга" cümləsini yazın.'],
 quiz:[{q:'"Тетрадь" deməkdir:',o:['Kitab','Dəftər','Çanta'],a:1},{q:'"Qələm" rusca necə yazılır?',o:['Карандаш','Сумка','Книга'],a:0}]},
 {id:'l15',emoji:'⏰',title:'Saat və vaxt',meta:'Vaxt ifadə etmək',desc:'Saatı soruşmaq və cavablandırmaq, gündəlik rejim sözləri ilə.',words:['Сколько времени? — Saat neçədir?','Час — Saat','Утро — Səhər','Вечер — Axşam','Ночь — Gecə'],hw:['Öz gündəlik rejiminizi (səhər/axşam) rusca yazın.','"Сколько времени?" sualını əzbərləyin.'],
 quiz:[{q:'"Утро" nə deməkdir?',o:['Axşam','Səhər','Gecə'],a:1},{q:'"Saat neçədir?" rusca necə deyilir?',o:['Сколько времени?','Час','Ночь'],a:0}]},
 {id:'l16',emoji:'🎭',title:'Səviyyə 2 Təkrarı',meta:'Ümumiləşdirmə + dialoq',desc:'2-ci səviyyənin mövzuları üzrə cüt-cüt dialoq qurma və kiçik tamaşa.',words:['Təkrar: günlər, ev, geyim','Təkrar: hava, fellər','Təkrar: məktəb əşyaları, vaxt'],hw:['8 yeni sözü dəftərə yazın.','Dostunuzla rusca kiçik dialoq qurun (3 cümlə).'],
 quiz:[{q:'Səviyyə 2-də neçə yeni mövzu öyrəndik?',o:['3','7','15'],a:1},{q:'"Мы идём" hansı mövzuya aiddir?',o:['Fellər','Rənglər','Heyvanlar'],a:0}]}
]},
{id:'lvl3',name:'Səviyyə 3 — İrəliləmiş',lessons:[
 {id:'l17',emoji:'💬',title:'Sadə dialoqlar',meta:'Danışıq vərdişləri',desc:'Restoranda, mağazada sadə dialoq qurma, rollu oyunlarla canlandırma.',words:['Сколько это стоит? — Bu neçəyədir?','Я хочу... — Mən istəyirəm...','Дайте, пожалуйста — Verin, lütfən','Хорошо — Yaxşı'],hw:['Mağazada alış-veriş dialoqu yazın (4 cümlə).','"Я хочу..." ilə 3 cümlə qurun.'],
 quiz:[{q:'"Сколько это стоит?" nə deməkdir?',o:['Bu neçəyədir?','Bu nədir?','Hara gedirsən?'],a:0},{q:'"Lütfən" rusca necə deyilir?',o:['Хорошо','Пожалуйста','Дайте'],a:1}]},
 {id:'l18',emoji:'🧩',title:'Sifətlər',meta:'Təsvir sözləri',desc:'Böyük, kiçik, gözəl, yaxşı kimi sifətlər, əşyaları təsvir etmə oyunu.',words:['Большой — Böyük','Маленький — Kiçik','Красивый — Gözəl','Хороший — Yaxşı','Плохой — Pis'],hw:['3 əşyanı sifətlərlə təsvir edin.','"Это большой дом" kimi cümlə qurun.'],
 quiz:[{q:'"Маленький" deməkdir:',o:['Böyük','Kiçik','Gözəl'],a:1},{q:'"Pis" rusca necə yazılır?',o:['Хороший','Плохой','Красивый'],a:1}]},
 {id:'l19',emoji:'📖',title:'Qısa hekayə',meta:'Oxu vərdişi',desc:'Sadə qısa hekayə oxuma və başa düşmə, şəkilli kitabçalarla.',words:['Однажды — Bir gün','Жил-был — Yaşayırdı','Конец — Son','Сказка — Nağıl'],hw:['Hekayəni oxuyub 2 sual yazın.','Öz qısa hekayənizi (3 cümlə) rusca yazmağa cəhd edin.'],
 quiz:[{q:'"Сказка" nə deməkdir?',o:['Nağıl','Son','Bir gün'],a:0},{q:'"Жил-был" hansı mənada işlənir?',o:['Bir gün yaşayırdı','Salam','Sağ ol'],a:0}]},
 {id:'l20',emoji:'🗣️',title:'Sual cümlələri',meta:'Sual qurma',desc:'Kim, nə, harada, niyə kimi sual sözləri ilə cümlə qurma.',words:['Кто? — Kim?','Что? — Nə?','Где? — Harada?','Почему? — Niyə?','Когда? — Nə vaxt?'],hw:['5 sual sözü ilə 5 sual yazın.','Dostunuza rusca 2 sual verin.'],
 quiz:[{q:'"Почему?" deməkdir:',o:['Niyə?','Kim?','Harada?'],a:0},{q:'"Nə vaxt?" rusca necə deyilir?',o:['Кто?','Когда?','Что?'],a:1}]},
 {id:'l21',emoji:'🌍',title:'Şəhər və nəqliyyat',meta:'Gündəlik həyat',desc:'Avtobus, maşın, küçə kimi şəhər və nəqliyyat sözləri.',words:['Город — Şəhər','Улица — Küçə','Автобус — Avtobus','Машина — Maşın','Метро — Metro'],hw:['Şəhərinizdə gördüyünüz nəqliyyatı rusca yazın.','"Я еду на автобусе" cümləsini yazın.'],
 quiz:[{q:'"Улица" nə deməkdir?',o:['Şəhər','Küçə','Metro'],a:1},{q:'"Maşın" rusca necə yazılır?',o:['Машина','Автобус','Город'],a:0}]},
 {id:'l22',emoji:'🎉',title:'Bayramlar',meta:'Mədəniyyət',desc:'Ad günü, Yeni il kimi bayram sözləri, təbrik ifadələri ilə.',words:['День рождения — Ad günü','Новый год — Yeni il','Поздравляю! — Təbrik edirəm!','Праздник — Bayram'],hw:['Bir bayramı rusca təbrik edin (1 cümlə).','Sevimli bayramınızı rusca yazın.'],
 quiz:[{q:'"Поздравляю!" deməkdir:',o:['Sağ ol','Təbrik edirəm!','Bağışla'],a:1},{q:'"Yeni il" rusca necə yazılır?',o:['Новый год','Праздник','День рождения'],a:0}]},
 {id:'l23',emoji:'🧠',title:'Qarışıq möhkəmləndirmə',meta:'Bütün mövzular',desc:'Bütün öyrənilən mövzulardan qarışıq tapşırıqlar və komanda oyunları.',words:['Bütün mövzuların təkrarı','Komanda yarışı','Sürətli cavab oyunu'],hw:['10 sual özünüz üçün yazıb cavablandırın.','Ən çətin hesab etdiyiniz 3 sözü təkrar edin.'],
 quiz:[{q:'Bu dərs nəyə həsr olunub?',o:['Yeni hərflər','Ümumi təkrar','Yeni rənglər'],a:1},{q:'24 dərsdən neçəsini bitirdik (bu dərslə)?',o:['20','23','24'],a:1}]},
 {id:'l24',emoji:'🏆',title:'Yekun: Bitirmə Dərsi',meta:'Final qiymətləndirməsi',desc:'Proqramın yekun dərsi — bütün biliklərin yoxlanılması və sertifikat təqdimatı.',words:['Поздравляю с окончанием! — Bitirməyiniz münasibətilə təbrik!','Молодец! — Əhsən!'],hw:['Proqram boyu öyrəndiyiniz 15 sözü siyahı şəklində yazın.','Valideynlərinizlə öyrəndiklərinizi nümayiş etdirin.'],
 quiz:[{q:'"Молодец!" nə deməkdir?',o:['Əhsən!','Sağol','Niyə?'],a:0},{q:'Proqram neçə dərsdən ibarətdir?',o:['12','18','24'],a:2}]}
]},
{id:'lvl4',name:'10-12 yaş — Dərin Qrammatika (rus dilində)',lessons:[
 {id:'l25',emoji:'📘',title:'Имя существительное: Род',meta:'Существительное и его род',desc:'Существительные в русском языке делятся на три рода: мужской, женский и средний. Род определяется по окончанию слова. Например: стол (м.р.), книга (ж.р.), окно (ср.р.).',words:['Стол (м.р.) — Stol','Книга (ж.р.) — Kitab','Окно (ср.р.) — Pəncərə','Учитель (м.р.) — Müəllim','Тетрадь (ж.р.) — Dəftər'],hw:['Найдите 5 слов мужского рода и 5 слов женского рода.','Определите род слов: яблоко, машина, дом.'],
 quiz:[{q:'Какого рода слово "книга"?',o:['Мужской','Женский','Средний'],a:1},{q:'Слово "окно" — это:',o:['Мужской род','Женский род','Средний род'],a:2}]},
 {id:'l26',emoji:'❓',title:'Падежи: Именительный и Винительный',meta:'Падежная система',desc:'Именительный падеж отвечает на вопрос «кто? что?» — это подлежащее. Винительный падеж отвечает на вопрос «кого? что?» — это прямое дополнение. Пример: Это стол (им.). Я вижу книгу (вин.).',words:['Кто? Что? — İmenitelnı sual','Кого? Что? — Vinitelnı sual','Я вижу книгу — Mən kitabı görürəm','Это стол — Bu stoldur'],hw:['Составьте 3 предложения в винительном падеже.','Подчеркните подлежащее в 3 предложениях из учебника.'],
 quiz:[{q:'На какой вопрос отвечает именительный падеж?',o:['Кто? Что?','Кого? Чего?','Где?'],a:0},{q:'"Я вижу книгу" — слово "книгу" в каком падеже?',o:['Именительный','Винительный','Родительный'],a:1}]},
 {id:'l27',emoji:'🏠',title:'Родительный падеж',meta:'Принадлежность',desc:'Родительный падеж отвечает на вопрос «кого? чего?» и часто обозначает принадлежность: дом отца, книга друга.',words:['Кого? Чего? — sual','Дом отца — Atanın evi','Книга друга — Dostun kitabı','Нет воды — Su yoxdur'],hw:['Составьте 3 словосочетания в родительном падеже.','Переведите на русский: "atanın maşını".'],
 quiz:[{q:'Родительный падеж отвечает на вопрос:',o:['Кто? Что?','Кого? Чего?','Куда?'],a:1},{q:'"Дом отца" показывает:',o:['Действие','Принадлежность','Цвет'],a:1}]},
 {id:'l28',emoji:'⏳',title:'Глагол: Настоящее время',meta:'Спряжение глаголов',desc:'Глаголы в настоящем времени изменяются по лицам и числам: я делаю, ты делаешь, он делает, мы делаем, они делают.',words:['Я делаю — Mən edirəm','Ты играешь — Sən oynayırsan','Он читает — O oxuyur','Мы говорим — Biz danışırıq','Они идут — Onlar gedirlər'],hw:['Проспрягайте глагол "играть" по всем лицам.','Составьте 3 предложения в настоящем времени.'],
 quiz:[{q:'"Они идут" — это какое время?',o:['Прошедшее','Настоящее','Будущее'],a:1},{q:'Глагол "делать" в форме "ты":',o:['Делаю','Делаешь','Делает'],a:1}]},
 {id:'l29',emoji:'⏰',title:'Глагол: Прошедшее и будущее',meta:'Времена глагола',desc:'Прошедшее время образуется с суффиксом -л: играл, читала. Будущее время — с глаголом «быть» или приставкой: будем играть, сыграет.',words:['Я играл — Mən oynadım','Она читала — O oxudu','Мы будем играть — Biz oynayacağıq','Он сыграет — O oynayacaq'],hw:['Напишите 3 предложения в прошедшем времени.','Напишите 3 предложения в будущем времени.'],
 quiz:[{q:'"Она читала" — какое время?',o:['Настоящее','Прошедшее','Будущее'],a:1},{q:'Будущее время глагола "играть" с "мы":',o:['Играли','Играем','Будем играть'],a:2}]},
 {id:'l30',emoji:'🎨',title:'Прилагательное: согласование',meta:'Согласование с существительным',desc:'Прилагательное согласуется с существительным в роде, числе и падеже: большой дом, большая книга, большое окно, большие дома.',words:['Большой дом — böyük ev','Большая книга — böyük kitab','Большое окно — böyük pəncərə','Красивые цветы — gözəl çiçəklər'],hw:['Подберите прилагательные к 5 существительным разного рода.','Составьте 3 словосочетания "прилагательное+существительное".'],
 quiz:[{q:'"Большая" сочетается со словом:',o:['Дом','Книга','Окно'],a:1},{q:'Прилагательное согласуется с существительным в:',o:['Цвете','Роде, числе, падеже','Времени'],a:1}]},
 {id:'l31',emoji:'🔢',title:'Числительные',meta:'Количественные и порядковые',desc:'Количественные числительные отвечают на вопрос «сколько?» (один, два, три), порядковые — «который?» (первый, второй, третий).',words:['Один, два, три — say','Первый, второй, третий — sıra','Сколько? — neçə?','Который? — neçənci?'],hw:['Напишите числа от 1 до 20 по-русски.','Напишите порядковые числительные от 1 до 10.'],
 quiz:[{q:'"Третий" — это числительное:',o:['Количественное','Порядковое'],a:1},{q:'"Сколько?" задаётся к числительному:',o:['Количественному','Порядковому'],a:0}]},
 {id:'l32',emoji:'📍',title:'Предлоги места и времени',meta:'Предлоги',desc:'Предлоги «в, на, под, за, через, после» показывают место или время действия: в школе, на столе, под столом, после урока, через час.',words:['В школе — məktəbdə','На столе — stolun üstündə','Под столом — stolun altında','После урока — dərsdən sonra','Через час — bir saatdan sonra'],hw:['Составьте 5 предложений с разными предлогами.','Подчеркните предлоги в тексте учебника.'],
 quiz:[{q:'"После урока" показывает:',o:['Место','Время','Цвет'],a:1},{q:'"Под столом" — какой предлог?',o:['На','Под','После'],a:1}]},
 {id:'l33',emoji:'🔗',title:'Сложное предложение',meta:'Союзы',desc:'Союзы «и, а, но, потому что» соединяют простые предложения в сложные: Я читаю, а он играет. Я устал, потому что много работал.',words:['И — və','А — amma','Но — lakin','Потому что — çünki'],hw:['Составьте 3 сложных предложения с союзами.','Найдите союзы в тексте учебника.'],
 quiz:[{q:'Союз "потому что" выражает:',o:['Причину','Время','Место'],a:0},{q:'"Я читаю, а он играет" — союз:',o:['И','А','Но'],a:1}]},
 {id:'l34',emoji:'🏆',title:'Итоговый урок',meta:'Повторение и сочинение',desc:'Итоговый урок — повторение всей грамматики: род, падежи, время глагола, прилагательные, числительные, предлоги, союзы. Напишите небольшое сочинение, используя изученные правила.',words:['Повторение — təkrar','Сочинение — inşa','Грамматика — qrammatika'],hw:['Напишите сочинение из 5-6 предложений на тему "Моя семья".','Используйте минимум 3 разных падежа в сочинении.'],
 quiz:[{q:'Сколько падежей вы изучили в этом блоке?',o:['1','3','6'],a:1},{q:'Итоговое задание — это:',o:['Тест','Сочинение','Игра'],a:1}]}
]}
];

/* =========================================================
   ADULT_LEVELS — Yeniyetmə/Böyük proqramı
   CEFR (Avropa Şurası Dil Çərçivəsi) əsasında: A1 → B2
   Faza 2: yalnız A1 hazırdır. A2/B1/B2 növbəti fazalarda əlavə olunacaq.
   ========================================================= */
const ADULT_LEVELS = [
{id:'a1',name:'A1 — Başlanğıc (CEFR)',lessons:[
 {id:'a1-1',emoji:'🤝',title:'Tanışlıq',meta:'Знакомство · CEFR A1.1',desc:'Rus dilində özünü təqdim etmək, ad soruşmaq və cavab vermək. "Здравствуйте" rəsmi, "Привет" qeyri-rəsmi salamlaşmadır — hansını nə vaxt işlətmək lazım olduğunu öyrənirik.',words:['Здравствуйте — Salam (rəsmi)','Меня зовут... — Mənim adım...','Как вас зовут? — Sizin adınız nədir?','Очень приятно — Çox şadam','Я из Азербайджана — Mən Azərbaycandanam'],hw:['Özünüzü rusca 4 cümlə ilə təqdim edin (ad, ölkə, şəhər, peşə).','Rəsmi və qeyri-rəsmi salamlaşmanı bir cədvəldə müqayisə edin.'],
 quiz:[{q:'"Меня зовут..." nə deməkdir?',o:['Mənim adım...','Sizin adınız...','Mən yaşayıram...'],a:0},{q:'Hansı forma rəsmidir?',o:['Привет','Здравствуйте','Пока'],a:1}]},
 {id:'a1-2',emoji:'🔤',title:'Fonetika: Sait və samitlər',meta:'Произношение · CEFR A1.1',desc:'Rus dilinin tələffüz qaydaları: vurğu (ударение) sözün mənasını dəyişə bilər (замок — qala / зáмок — kilid). Yumşaq (ь) və sərt işarələr (ъ) samitlərin səsini dəyişir.',words:['Замок — qala (vurğu 2-ci hecada)','Зáмок — kilid (vurğu 1-ci hecada)','Мать — ana (yumşaq т)','Съезд — qurultay (ъ ilə ayrılma)','Ударение — vurğu'],hw:['5 sözdə vurğunun yerini işarələyin (lüğətdən).','Web Speech səsləndirmə ilə 10 sözü dinləyib təkrarlayın.'],
 quiz:[{q:'Rus dilində vurğu sözün mənasını:',o:['Heç vaxt dəyişmir','Dəyişə bilər','Yalnız yazıda dəyişir'],a:1},{q:'"Ь" işarəsi nəyi bildirir?',o:['Sərtlik','Yumşaqlıq','Uzunluq'],a:1}]},
 {id:'a1-3',emoji:'🧍',title:'Fe\'l "быть" və şəxs əvəzlikləri',meta:'Глагол "быть" · CEFR A1.1',desc:'"Быть" (olmaq) feli rus dilində indiki zamanda adətən buraxılır: "Я студент" (Mən tələbəyəm) — "являюсь" deyilmir. Şəxs əvəzlikləri: я, ты, он/она, мы, вы, они.',words:['Я — Mən','Ты — Sən','Он / Она — O (kişi/qadın)','Мы — Biz','Вы — Siz','Они — Onlar'],hw:['6 şəxs əvəzliyi ilə 6 cümlə qurun ("Я студент", "Он врач" kimi).','"Кто вы?" sualına öz peşənizlə cavab yazın.'],
 quiz:[{q:'"Я студент" cümləsində "являюсь" (olmaq feli) niyə yoxdur?',o:['Səhvdir','İndiki zamanda buraxılır','Yalnız kitab dilində olur'],a:1},{q:'"Она" hansı əvəzlikdir?',o:['Mən','O (qadın)','Siz'],a:1}]},
 {id:'a1-4',emoji:'📇',title:'İsmin cinsi',meta:'Род существительных · CEFR A1.2',desc:'Rus isimlərinin 3 cinsi var: kişi (мужской — samitlə bitir: стол), qadın (женский — -а/-я ilə bitir: книга), orta (средний — -о/-е ilə bitir: окно). Cinsi bilmək sifət və fel uzlaşması üçün vacibdir.',words:['Стол (м.р.) — Stol','Книга (ж.р.) — Kitab','Окно (ср.р.) — Pəncərə','Учитель (м.р.) — Müəllim','Дверь (ж.р., istisna) — Qapı'],hw:['10 yeni sözün cinsini müəyyən edin (lüğətdən seçin).','3 istisna sözü tapıb yazın (yumşaq işarə ilə bitən qadın cinsi sözlər).'],
 quiz:[{q:'"-а" ilə bitən söz adətən hansı cinsdəndir?',o:['Kişi','Qadın','Orta'],a:1},{q:'"Окно" hansı cinsdəndir?',o:['Kişi','Qadın','Orta'],a:2}]},
 {id:'a1-5',emoji:'🔢',title:'Rəqəmlər və qiymətlər',meta:'Числительные · CEFR A1.2',desc:'1-100 arası rəqəmlər və qiymət soruşmaq: "Сколько стоит?" (Neçəyədir?). Rus dilində rəqəmdən sonra isim forması dəyişir (1 rubl, 2 rublya, 5 rubley) — bu, A2-də dərinləşdiriləcək.',words:['Один, два, три... десять — 1-10','Двадцать, тридцать — 20, 30','Сто — 100','Сколько стоит? — Neçəyədir?','Это стоит 10 манат — Bu 10 manatdır'],hw:['1-100 arası 15 rəqəmi rusca yazın.','Mağazada 3 əşyanın qiymətini soruşan dialoq qurun.'],
 quiz:[{q:'"Сколько стоит?" nə deməkdir?',o:['Neçəyədir?','Neçə yaşındasan?','Saat neçədir?'],a:0},{q:'"100" rusca necə yazılır?',o:['Десять','Сто','Тридцать'],a:1}]},
 {id:'a1-6',emoji:'👔',title:'Peşələr və iş',meta:'Профессии · CEFR A1.2',desc:'Əsas peşə adları və "Kim işləyirsiniz?" sualı: "Кем вы работаете?" — cavab isə Творительный падeж (yaradıcı hal) ilə verilir: "Я работаю врачом" (Mən həkim işləyirəm).',words:['Врач — Həkim','Учитель — Müəllim','Инженер — Mühəndis','Программист — Proqramçı','Кем вы работаете? — Kim işləyirsiniz?'],hw:['Öz peşənizi "Я работаю..." forması ilə yazın.','5 peşə adını rusca-azərbaycanca lüğətə əlavə edin.'],
 quiz:[{q:'"Кем вы работаете?" sualının mənası:',o:['Harada yaşayırsınız?','Kim işləyirsiniz?','Neçə yaşındasınız?'],a:1},{q:'"Я работаю врачом" — "врачом" hansı halda?',o:['İmenitelnı','Yaradıcı (Творительный)','Vinitelnı'],a:1}]},
 {id:'a1-7',emoji:'🛒',title:'Mağazada / Alış-veriş',meta:'В магазине · CEFR A1.3',desc:'Mağazada real dialoq: nə istədiyini demək, qiymət soruşmaq, "Dayте, пожалуйста" ilə xahiş etmək. Bu dərs tam dialoq simulyasiyası ilə işlənir.',words:['Дайте, пожалуйста — Verin, lütfən','У вас есть...? — Sizdə var mı...?','Я возьму это — Mən bunu götürəcəm','Наличными или картой? — Nəğd yoxsa kartla?','Вот, пожалуйста — Buyurun'],hw:['Mağazada tam dialoq yazın (6-8 replika).','"У вас есть...?" ilə 3 sual qurun.'],
 quiz:[{q:'"Наличными или картой?" nə soruşur?',o:['Ödəniş üsulunu','Ünvanı','Qiyməti'],a:0},{q:'"Дайте, пожалуйста" hansı funksiyanı daşıyır?',o:['Salamlaşma','Nəzakətli xahiş','Vidalaşma'],a:1}]},
 {id:'a1-8',emoji:'🍽️',title:'Restoranda',meta:'В ресторане · CEFR A1.3',desc:'Restoranda sifariş vermək, menyu haqqında sual vermək, hesab istəmək. "Я хотел(а) бы..." — nəzakətli istək forması ("Я хочу" daha sərtdir).',words:['Я хотел(а) бы... — İstərdim ki...','Меню, пожалуйста — Menyu, lütfən','Что вы порекомендуете? — Nə tövsiyə edərsiniz?','Счёт, пожалуйста — Hesab, lütfən','Приятного аппетита! — Nuş olsun!'],hw:['Restoranda sifariş dialoqu yazın (5 replika).','"Я хотел(а) бы..." ilə 3 nəzakətli istək cümləsi qurun.'],
 quiz:[{q:'"Я хотел бы" ilə "Я хочу" arasındakı fərq:',o:['Fərq yoxdur','Birinci daha nəzakətlidir','İkinci daha nəzakətlidir'],a:1},{q:'"Счёт, пожалуйста" nə deməkdir?',o:['Menyu, lütfən','Hesab, lütfən','Su, lütfən'],a:1}]},
 {id:'a1-9',emoji:'🧭',title:'Şəhərdə istiqamət',meta:'В городе · CEFR A1.3',desc:'Yol soruşmaq və istiqamət göstərmək: налево (sola), направо (sağa), прямо (düz). "Как пройти..." — piyada gedərkən, "Как проехать..." — nəqliyyatla gedərkən işlənir.',words:['Как пройти до...? — ...necə getmək olar (piyada)','Налево — Sola','Направо — Sağa','Прямо — Düz','Это далеко? — Bu uzaqdır?'],hw:['Öz məhəllənizdən mərkəzə yol təsviri yazın (rusca).','Xəritə üzərində 3 istiqamət cümləsi qurun.'],
 quiz:[{q:'"Направо" nə deməkdir?',o:['Sola','Sağa','Düz'],a:1},{q:'"Как пройти" hansı halda işlənir?',o:['Nəqliyyatla','Piyada','Təyyarə ilə'],a:1}]},
 {id:'a1-10',emoji:'📆',title:'Gündəlik rutin',meta:'Распорядок дня · CEFR A1.4',desc:'Gündəlik hərəkətləri təsvir etmək üçün indiki zaman fellərinin şəxslərə görə dəyişməsi: вставать (durmaq), завтракать (səhər yeməyi yemək), работать (işləmək) və s. Refleksiv fellər (-ся) ilə tanışlıq.',words:['Я встаю в 7 часов — Mən saat 7-də dururam','Я завтракаю — Mən səhər yeməyi yeyirəm','Я иду на работу — Mən işə gedirəm','Я ложусь спать — Mən yatmağa gedirəm (-ся feli)'],hw:['Öz gündəlik rejiminizi 6 cümlə ilə rusca yazın.','-ся ilə bitən 3 fel tapıb mənasını yazın.'],
 quiz:[{q:'"-ся" şəkilçisi felə nə əlavə edir?',o:['Keçmiş zaman mənası','Refleksivlik (özünə yönəlmə)','Cəm mənası'],a:1},{q:'"Я иду на работу" nə deməkdir?',o:['Mən evə gedirəm','Mən işə gedirəm','Mən yatıram'],a:1}]},
 {id:'a1-11',emoji:'🌦️',title:'Hava və fəsillər',meta:'Погода и времена года · CEFR A1.4',desc:'Hava haqqında danışmaq üçün şəxssiz cümlələr: "На улице холодно" (Küçədə soyuqdur) — burada fail yoxdur, bu, rus dilinə xas bir quruluşdur.',words:['На улице холодно — Küçədə soyuqdur','Идёт дождь — Yağış yağır','Сегодня солнечно — Bu gün günəşlidir','Зимой холодно, летом жарко — Qışda soyuq, yayda isti'],hw:['4 fəsli hava şəraiti ilə təsvir edən 4 cümlə yazın.','"Идёт дождь/снег" strukturunu izah edin.'],
 quiz:[{q:'"На улице холодно" cümləsində fail (kim?) varmı?',o:['Bəli, "улица"','Xeyr, şəxssiz cümlədir','Bəli, gizli "я"'],a:1},{q:'"Идёт дождь" hərfi mənası:',o:['Yağış gedir','Yağış yağır','Yağış dayanır'],a:1}]},
 {id:'a1-12',emoji:'🏆',title:'A1 Yekun: Özünütəqdimat və keçid testi',meta:'Итоговый тест A1 · CEFR A1 → A2',desc:'A1 səviyyəsinin bütün mövzularını birləşdirən yekun tapşırıq: tam özünütəqdimat mətni (ad, peşə, ailə, gündəlik rejim, hava) yazmaq və A2 səviyyəsinə keçid testi.',words:['Итог — Yekun','Переход на уровень А2 — A2 səviyyəsinə keçid','Поздравляем! — Təbrik edirik!'],hw:['8-10 cümləlik tam özünütəqdimat mətni yazın (bütün A1 mövzularından istifadə edərək).','Öyrəndiyiniz 30 sözü təkrarlayıb özünüzü yoxlayın.'],
 quiz:[{q:'A1 səviyyəsində neçə əsas mövzu keçdik?',o:['6','12','20'],a:1},{q:'A1-dən sonra hansı səviyyəyə keçilir?',o:['B1','A2','B2'],a:1}]}
]}
];
