/* =========================================================
   AN Rus Dili Platforması — Dərs Məlumatları
   CHILD_LEVELS: 7-12 yaş proqramı (mövcud, dəyişməz saxlanıb)
   ADULT_LEVELS: Yeniyetmə/Böyük proqramı — CEFR (A1-B2) əsaslı
   ========================================================= */

const CHILD_LEVELS = [
{id:'lvl1',name:'Səviyyə 1 — Başlanğıc',lessons:[
 {id:'l1',emoji:'🔤',title:'Əlifba 1: А-Ё',meta:'Hərflər və səslər (1/5)',desc:'Rus əlifbası 33 hərfdən ibarətdir və biz onu 5 dərsə bölərək tam öyrənəcəyik. Bu dərsdə ilk 7 hərflə tanış oluruq: А, Б, В, Г, Д, Е, Ё. Hər hərfin öz səsi var və rus dilində demək olar ki, hər hərf yazıldığı kimi oxunur (Azərbaycan dilinə bənzər cəhətdir). Uşaq hər hərfi rəngli kartlarla, həmin hərflə başlayan sözün şəkli ilə və səs təqlidi ilə (heyvan səsləri, təbiət səsləri) yadda saxlayır. Хərflərin həm böyük (Б), həm kiçik (б) formasını yazmaq vacibdir.',words:['А — Аист (Leylək)','Б — Банан (Banan)','В — Волк (Qurd)','Г — Гриб (Göbələk)','Д — Дом (Ev)','Е — Ель (Şam ağacı)','Ё — Ёж (Kirpi)'],hw:['Dəftərdə А,Б,В,Г,Д,Е,Ё hərflərini böyük və kiçik formada 5 dəfə yazın — hərfin formasını əl əzələsinə "öyrətmək" üçün təkrar vacibdir.','Hər hərflə başlayan bir əşyanın şəklini çəkin və altına hərfi yazın.','Valideynlə birlikdə evdə 3 əşya tapıb, onların rusca adının hansı hərflə başladığını deyin.'],
 quiz:[{q:'"Дом" sözü nə deməkdir?',o:['Ev','İt','Günəş'],a:0},{q:'"Волк" hansı hərflə başlayır?',o:['А','В','Д'],a:1},{q:'"Ёж" nə deməkdir?',o:['Kirpi','Qurd','Ev'],a:0},{q:'Rus əlifbasında cəmi neçə hərf var?',o:['26','33','30'],a:1}]},
 {id:'l2',emoji:'🔤',title:'Əlifba 2: Ж-М',meta:'Hərflər və səslər (2/5)',desc:'İkinci qrup hərflər: Ж, З, И, Й, К, Л, М. Bunlardan Ж (jujuk kimi bir səs — "j") və Й (qısa "i", "y" səsinə yaxın) azərbaycandilli uşaqlar üçün bir az fərqli səslənə bilər, ona görə bu hərflərə xüsusi diqqət ayırırıq. И və Й-ni qarışdırmamaq üçün müqayisəli məşq edirik: "мой" (mənim) sözündə Й qısadır, "мир" (dünya) sözündə И uzundur.',words:['Ж — Жук (Böcək)','З — Заяц (Dovşan)','И — Игра (Oyun)','Й — Мой (Mənim)','К — Кот (Pişik)','Л — Лиса (Tülkü)','М — Мама (Ana)'],hw:['7 hərfi böyük/kiçik formada dəftərə yazın.','"И" və "Й" ilə olan 2 sözü tapıb səsləndirmə düyməsi ilə dinləyin, fərqi hiss etməyə çalışın.','Otaqda bu hərflərlə başlayan 3 əşya/heyvan adı tapın.'],
 quiz:[{q:'"Жук" nə deməkdir?',o:['Böcək','Tülkü','Pişik'],a:0},{q:'"Кот" hansı heyvandır?',o:['Dovşan','Pişik','Böcək'],a:1},{q:'"Мой" hansı hərflə bitir?',o:['И','Й','М'],a:1},{q:'"Лиса" nə deməkdir?',o:['Tülkü','Ana','Oyun'],a:0}]},
 {id:'l3',emoji:'🔤',title:'Əlifba 3: Н-У',meta:'Hərflər və səslər (3/5)',desc:'Üçüncü qrup: Н, О, П, Р, С, Т, У. Bu hərflər arasında Р hərfi diqqət tələb edir — rus dilində "Р" Azərbaycan dilindəki "r"-dən bir qədər daha "diyirlənən" tələffüz olunur (dilucu titrəyişi ilə). Bunu öyrənmək üçün "рыба" (balıq) sözü üzərində məşq edirik. О hərfi vurğusuz hecada bəzən "a" kimi eşidilir (bu, irəlidə fonetika dərsində daha ətraflı izah olunacaq).',words:['Н — Нос (Burun)','О — Окно (Pəncərə)','П — Папа (Ata)','Р — Рыба (Balıq)','С — Солнце (Günəş)','Т — Тигр (Pələng)','У — Утка (Ördək)'],hw:['7 hərfi dəftərə yazın, hər birini 5 dəfə təkrarlayın.','"Рыба" sözünü 🔊 düyməsi ilə 3 dəfə dinləyib, Р səsini təqlid etməyə çalışın.','"Солнце" (günəş) sözü ilə bir cümlə — "Это солнце" (Bu günəşdir) — yazın.'],
 quiz:[{q:'"Тигр" nə deməkdir?',o:['Pələng','Ördək','Burun'],a:0},{q:'"Окно" nəyə deyilir?',o:['Qapı','Pəncərə','Divar'],a:1},{q:'"Папа" kim deməkdir?',o:['Ana','Ata','Baba'],a:1},{q:'Bu dərsdə neçə yeni hərf öyrəndik?',o:['5','7','10'],a:1}]},
 {id:'l4',emoji:'🔤',title:'Əlifba 4: Ф-Щ',meta:'Hərflər və səslər (4/5)',desc:'Dördüncü qrup — Azərbaycan dilində olmayan bəzi səslər buradadır: Ф, Х, Ц, Ч, Ш, Щ. Ц hərfi "ts" səsi verir (sitat sözündəki kimi), Щ isə uzun və yumşaq "şç" səsidir — bu, ən çətin rus səslərindən biridir və "щенок" (bala it) sözü üzərində məşq edilir. Ш isə sərt "ş" səsidir (Ç fərqli olaraq). Bu iki səsi (Ш/Щ) müqayisəli dinləmək faydalıdır.',words:['Ф — Флаг (Bayraq)','Х — Хлеб (Çörək)','Ц — Цирк (Sirk)','Ч — Час (Saat)','Ш — Шар (Şar)','Щ — Щенок (Bala it)'],hw:['6 hərfi dəftərə yazın.','"Ш" və "Щ" ilə 1-ər söz tapıb 🔊 ilə dinləyin, səs fərqini valideynə izah etməyə çalışın.','"Хлеб" (çörək) sözünü rəsimlə əlaqələndirib boyayın.'],
 quiz:[{q:'"Цирк" nə deməkdir?',o:['Sirk','Bayraq','Saat'],a:0},{q:'"Щенок" nə deməkdir?',o:['Bala pişik','Bala it','Bala qurd'],a:1},{q:'"Шар" nəyə deyilir?',o:['Şar','Bayraq','Çörək'],a:0},{q:'"Х" hərfi hansı sözdə var?',o:['Хлеб','Час','Флаг'],a:0}]},
 {id:'l5',emoji:'🔤',title:'Əlifba 5: Ъ-Я',meta:'Hərflər və səslər (5/5)',desc:'Son qrup — əlifbanın ən özünəməxsus üzvləri: Ъ (sərt işarə), Ы (xüsusi Azərbaycan dilində analoqu olmayan səs, "ı" ilə "u" arası), Ь (yumşaq işarə — özü səs bildirmir, əvvəlki samiti yumşaldır), Э, Ю, Я. Ъ və Ь hərfləri "işarə" adlanır, çünki onların öz səsi yoxdur, sadəcə əvvəlki samitin tələffüzünü dəyişirlər (Ъ ayırır/sərtləşdirir, Ь yumşaldır). Bu dərslə tam əlifbanı (33 hərf) bitirmiş oluruq!',words:['Ъ — Подъезд (Giriş qapısı)','Ы — Мы (Biz)','Ь — Соль (Duz)','Э — Эхо (Əks-səda)','Ю — Юла (Fırfıra)','Я — Яблоко (Alma)'],hw:['6 hərfi dəftərə yazın, bununla A-dan Я-ya bütün əlifbanı yazmış olacaqsınız — tam əlifbanı bir səhifədə sıra ilə yazın.','"Мы" və "Ты" sözlərini müqayisə edib, "Ы" səsini 🔊 ilə dinləyin.','Yuxarı bölmədəki "Rus Əlifbası" hissəsinə keçib 33 hərfin hamısını sırayla klikləyərək dinləyin — bu, təkrar üçün əladır.'],
 quiz:[{q:'"Яблоко" nə deməkdir?',o:['Alma','Duz','Biz'],a:0},{q:'Ъ və Ь hərflərinin özlərinin səsi varmı?',o:['Bəli','Xeyr, əvvəlki samiti dəyişirlər','Yalnız Ъ-nin var'],a:1},{q:'"Соль" nə deməkdir?',o:['Duz','Şəkər','Su'],a:0},{q:'Bu 5 dərslə cəmi neçə hərf öyrəndik?',o:['26','30','33'],a:2}]},
 {id:'l6',emoji:'👋',title:'Salamlaşma',meta:'Gündəlik ifadələr',desc:'İndi əlifbanı bildiyimizə görə, ilk sözlərimizi və cümlələrimizi qura bilərik. Salamlaşma rus dilində iki formada olur: rəsmi (Здравствуйте — böyüklərə, tanımadığımız insanlara) və qeyri-rəsmi (Привет — dostlara, həmyaşıdlara). "Как дела?" sualına adətən "Хорошо, спасибо!" (Yaxşı, sağ ol!) və ya "Нормально" (Normaldır) deyə cavab verilir. Vidalaşarkən isə "До свидания" (rəsmi) və ya "Пока" (qeyri-rəsmi, "hələlik" mənasında) işlədilir.',words:['Привет — Salam (dost)','Здравствуйте — Salam (hörmətlə)','Как дела? — Necəsən?','Хорошо, спасибо! — Yaxşı, sağ ol!','Спасибо — Sağ ol','Пожалуйста — Buyurun/Xahiş edirəm','До свидания — Sağ ol (rəsmi)','Пока — Sağ ol (dost)'],hw:['"Привет, как дела?" — "Хорошо, спасибо!" dialoqunu 3 dəfə yazıb əzbərləyin.','Ailə üzvü ilə — biriniz rəsmi, digəriniz qeyri-rəsmi salamlaşaraq — rollu oyun oynayın.','"Спасибо" — "Пожалуйста" cütünün nə vaxt işləndiyini bir cümlə ilə izah edin.'],
 quiz:[{q:'"Спасибо" nə deməkdir?',o:['Sağ ol','Salam','Bağışla'],a:0},{q:'"Necəsən?" rusca necə deyilir?',o:['Привет','Как дела?','До свидания'],a:1},{q:'Böyüklərə hansı salamlaşma forması işlədilir?',o:['Привет','Здравствуйте','Пока'],a:1},{q:'"Пока" hansı mənada işlənir?',o:['Salam (dostcasına)','Sağ ol (dostcasına, vidalaşma)','Bağışla'],a:1}]},
 {id:'l7',emoji:'👨‍👩‍👧‍👦',title:'Ailə üzvləri',meta:'Ailə sözləri',desc:'Ailə üzvlərinin adları — ən çox işlənən və uşaqların ilk öyrəndiyi söz qrupudur. Rus dilində "mənim" mənasını vermək üçün "мой" (kişi cinsi üçün: мой папа) və "моя" (qadın cinsi üçün: моя мама) fərqli işlədilir — bu, sonrakı dərslərdə öyrənəcəyimiz "ismin cinsi" mövzusunun ilk toxunuşudur. Geniş ailə sözləri (tetya-dayı, tədə-əmi) da əlavə edilib ki, uşaq təkcə əsas ailəni deyil, geniş qohumluq dairəsini də tanısın.',words:['Мама — Ana (моя мама)','Папа — Ata (мой папа)','Брат — Qardaş','Сестра — Bacı','Бабушка — Nənə','Дедушка — Baba','Тётя — Xala/Bibi','Дядя — Dayı/Əmi'],hw:['Ailənizin şəklini çəkin, hər üzvün adını rusca yazın və "мой/моя" düzgün işlədin.','"Это моя мама. Это мой папа." kimi 4 cümlə qurun (fərqli ailə üzvləri ilə).','Nənə-baba, xala-dayı sözlərini rus və Azərbaycan dilində müqayisə edən kiçik cədvəl çəkin.'],
 quiz:[{q:'"Брат" kim deməkdir?',o:['Bacı','Qardaş','Ata'],a:1},{q:'"Nənə" rusca necə yazılır?',o:['Дедушка','Бабушка','Мама'],a:1},{q:'"Мой" sözü hansı halda işlənir?',o:['Qadın cinsi ilə','Kişi cinsi ilə','Hər ikisi ilə eyni'],a:1},{q:'"Тётя" kim deməkdir?',o:['Dayı','Xala/Bibi','Nənə'],a:1}]},
 {id:'l8',emoji:'🧍',title:'Bədən üzvləri',meta:'İnsan bədəni',desc:'Bədən üzvlərinin adları — özünü təsvir etmək və sağlamlıq haqqında sadə cümlələr qurmaq üçün əsasdır ("başım ağrıyır" kimi ifadələri irəlidə bu sözlər üzərində quracağıq). Uşaqlarla bu mövzu adətən "Boya nəyi göstərir?" oyunu, güzgü qarşısında bədən üzvlərini göstərmə məşqi ilə keçirilir — hərəkətlə birlikdə öyrənmə yaddaşı gücləndirir.',words:['Голова — Baş','Глаза — Gözlər','Нос — Burun','Рот — Ağız','Уши — Qulaqlar','Руки — Əllər','Ноги — Ayaqlar'],hw:['Öz bədəninizi güzgüdə göstərərək 7 sözü rusca deyin və dəftərə yazın.','İnsan fiqurunu çəkib bədən üzvlərini rusca adlandırın.','"У меня есть..." (mənim ... var) qəlibi ilə 2 cümlə qurmağa çalışın (məs. "У меня есть нос").'],
 quiz:[{q:'"Голова" nə deməkdir?',o:['Baş','Əl','Ayaq'],a:0},{q:'"Глаза" nəyi bildirir?',o:['Qulaqlar','Gözlər','Ağız'],a:1},{q:'"Руки" nə deməkdir?',o:['Ayaqlar','Əllər','Baş'],a:1},{q:'Neçə bədən üzvü öyrəndik?',o:['5','7','10'],a:1}]},
 {id:'l9',emoji:'🐾',title:'Heyvanlar',meta:'Heyvan adları',desc:'Ev heyvanları (домашние животные) və vəhşi heyvanlar (дикие животные) olaraq iki qrupa ayrılır — bu təsnifat uşağa kateqoriya ilə düşünməyi öyrədir. Hər heyvanın öz səsi rus dilində fərqli təqlid olunur: məsələn, pişik "мяу", it isə "гав-гав" deyir — bu, Azərbaycan dilindəki səs təqlidlərindən fərqlənə bilər və əyləncəli müqayisə mövzusudur.',words:['Кошка — Pişik (ev heyvanı)','Собака — İt (ev heyvanı)','Лошадь — At (ev heyvanı)','Медведь — Ayı (vəhşi)','Заяц — Dovşan (vəhşi)','Волк — Qurd (vəhşi)','Слон — Fil (vəhşi)'],hw:['5 heyvan adını rusca yazın və hər birinin ev/vəhşi olduğunu qeyd edin.','Sevimli heyvanınızı rusca 1 cümlə ilə təsvir edin: "Мой любимый — кошка" (Mənim sevimlim pişikdir).','Pişik və itin rusca səs təqlidini (мяу, гав-гав) valideynə göstərin.'],
 quiz:[{q:'"Собака" deməkdir:',o:['Pişik','İt','At'],a:1},{q:'"Ayı" rusca necə yazılır?',o:['Медведь','Заяц','Кошка'],a:0},{q:'"Слон" hansı heyvandır?',o:['Fil','Qurd','At'],a:0},{q:'"Домашние животные" nə deməkdir?',o:['Vəhşi heyvanlar','Ev heyvanları','Quşlar'],a:1}]},
 {id:'l10',emoji:'🎨',title:'Rənglər',meta:'Əsas rənglər',desc:'Əsas rənglər — rəngləmə, boyama və əşyaları təsvir etmə tapşırıqları üçün baza sözlərdir. Diqqət: rus dilində sifət (bu halda rəng) isimlə cinsə görə uzlaşır — "красный" (kişi/neytral, məs. дом), "красная" (qadın, məs. машина), "красное" (orta, məs. яблоко). Bu dərsdə sadəcə əsas (kişi cinsi) formanı öyrədirik, tam uzlaşma irəlidə "sifətin uzlaşması" mövzusunda ətraflı keçiləcək.',words:['Красный — Qırmızı','Синий — Göy','Жёлтый — Sarı','Зелёный — Yaşıl','Белый — Ağ','Чёрный — Qara','Оранжевый — Narıncı','Розовый — Çəhrayı'],hw:['8 rəngi dəftərə yazıb, hər birinin yanında həmin rəngdə kiçik kvadrat rəngləyin.','Otağınızdakı 5 əşyanın rəngini rusca yazın.','"Это красный дом" kimi 2 cümlə qurun.'],
 quiz:[{q:'"Жёлтый" nə rəngdir?',o:['Qırmızı','Sarı','Göy'],a:1},{q:'"Yaşıl" rusca necə yazılır?',o:['Зелёный','Белый','Синий'],a:0},{q:'"Оранжевый" hansı rəngdir?',o:['Çəhrayı','Narıncı','Qara'],a:1},{q:'"Чёрный" nə deməkdir?',o:['Ağ','Qara','Göy'],a:1}]},
 {id:'l11',emoji:'🔢',title:'Rəqəmlər 1-20',meta:'Say-say oyunu',desc:'Rəqəmlər 1-dən 20-yə qədər — əvvəlki versiyada yalnız 1-10 idi, indi 20-yə qədər genişləndirdik ki, uşaq daha real hesablama bacarığı qazansın. 11-19 arası rəqəmlər maraqlıdır: onlar "onbir" mənasında "один+надцать" modelinə uyğun düzəlir (odinnadцать = 11). 20 isə tamamilə fərqli söz olan "двадцать"-dır. Say-say oyunu, barmaqla sayma, pillə sayma kimi fəaliyyətlərlə möhkəmləndirilir.',words:['Один, Два, Три — 1,2,3','Четыре, Пять — 4,5','Шесть, Семь, Восемь — 6,7,8','Девять, Десять — 9,10','Одиннадцать — 11','Пятнадцать — 15','Двадцать — 20'],hw:['1-dən 20-yə qədər rəqəmləri rusca yazın.','Otaqdaki əşyaları sayaraq rusca uca səslə deyin (ən azı 10-a qədər).','11-19 arası rəqəmlərin "-надцать" ilə bitdiyini müşahidə edib, 3 nümunə yazın.'],
 quiz:[{q:'"Три" hansı rəqəmdir?',o:['2','3','5'],a:1},{q:'"5" rusca necə deyilir?',o:['Четыре','Пять','Два'],a:1},{q:'"Двадцать" hansı rəqəmdir?',o:['12','20','10'],a:1},{q:'"Одиннадцать" hansı rəqəmdir?',o:['10','11','19'],a:1}]},
 {id:'l12',emoji:'🍎',title:'Yeməklər və meyvələr',meta:'Qida adları',desc:'Ən çox işlənən yemək və meyvə-tərəvəz adları. "Я хочу..." (Mən istəyirəm...) qəlibi ilə istək bildirməyi öyrədirik — bu, uşağın gündəlik həyatda (yemək masasında) real işlədə biləcəyi ilk tam cümlələrdən biridir. Meyvə və tərəvəzləri ayrıca qruplaşdırmaq (фрукты/овощи) təsnifat düşüncəsini inkişaf etdirir.',words:['Яблоко — Alma (meyvə)','Банан — Banan (meyvə)','Хлеб — Çörək','Молоко — Süd','Сыр — Pendir','Вода — Su','Морковь — Yerkökü (tərəvəz)','Огурец — Xiyar (tərəvəz)'],hw:['Sevdiyiniz 3 yeməyi rusca yazın və meyvə/tərəvəz olduğunu qeyd edin.','"Я хочу молоко" qəlibi ilə 3 fərqli yemək üçün cümlə qurun.','Ailənizlə süfrədə 3 əşyanın rusca adını uca səslə deyin.'],
 quiz:[{q:'"Хлеб" nə deməkdir?',o:['Çörək','Su','Alma'],a:0},{q:'"Süd" rusca necə yazılır?',o:['Сыр','Молоко','Вода'],a:1},{q:'"Морковь" nədir?',o:['Yerkökü','Xiyar','Alma'],a:0},{q:'"Я хочу" nə deməkdir?',o:['Mən istəyirəm','Mən yeyirəm','Mən gedirəm'],a:0}]},
 {id:'l13',emoji:'🧸',title:'Oyuncaqlar və sadə fellər',meta:'Oyuncaqlar, sevmək/istəmək',desc:'Oyuncaq adları ilə yanaşı, iki əsas fel öyrənilir: любить (sevmək) və хотеть (istəmək). "Я люблю..." (Mən sevirəm...) qəlibi ilə uşaq öz sevimli oyuncağı haqda danışa bilir. Bu, tam mənalı fel+isim birləşməsi qurmağın ilk addımıdır və növbəti səviyyələrdə fellərin dəyişməsi (spряжение) mövzusuna zəmin hazırlayır.',words:['Игрушка — Oyuncaq','Мяч — Top','Кукла — Kukla','Машинка — Kiçik maşın','Я люблю... — Mən sevirəm...','Я хочу... — Mən istəyirəm...'],hw:['"Я люблю мяч" kimi öz sevimli oyuncağınızla cümlə qurun.','4 oyuncaq adını rusca yazıb şəklini çəkin.','"Я хочу" və "Я люблю" arasındakı fərqi öz sözlərinizlə izah edin (istək / sevgi).'],
 quiz:[{q:'"Игрушка" nə deməkdir?',o:['Oyuncaq','Kitab','Top'],a:0},{q:'"Я люблю" nə deməkdir?',o:['Mən istəyirəm','Mən sevirəm','Mən oynayıram'],a:1},{q:'"Кукла" nədir?',o:['Top','Kukla','Maşın'],a:1},{q:'"Машинка" nə deməkdir?',o:['Böyük maşın','Kiçik maşın','Velosiped'],a:1}]},
 {id:'l14',emoji:'🌞',title:'Təbiət və göy cismləri',meta:'Sadə təbiət sözləri',desc:'Səma və təbiətlə bağlı ilk sözlər: günəş, ay, ulduz, göy, bulud. Bu sözlər həm real dünyanı təsvir etmək, həm də sonrakı "hava" mövzusuna (Səviyyə 2) körpü rolunu oynayır. Axşam səmasına baxaraq ulduzları saymaq kimi əyləncəli tapşırıqla möhkəmləndirilir.',words:['Солнце — Günəş','Луна — Ay','Звезда — Ulduz','Небо — Səma/Göy','Облако — Bulud','Дерево — Ağac'],hw:['Bu 6 sözü dəftərə yazıb, hər birinin kiçik rəsmini çəkin.','Axşam səmasına baxıb "Я вижу луну" (Ayı görürəm) kimi 1 cümlə yazın.','"Солнце" və "Луна" arasındakı fərqi (gündüz/gecə) rusca 1 cümlə ilə izah edin.'],
 quiz:[{q:'"Луна" nə deməkdir?',o:['Ay','Günəş','Ulduz'],a:0},{q:'"Небо" nəyi bildirir?',o:['Yer','Səma','Su'],a:1},{q:'"Дерево" nə deməkdir?',o:['Ağac','Çiçək','Ot'],a:0},{q:'"Звезда" nədir?',o:['Bulud','Ulduz','Ay'],a:1}]},
 {id:'l15',emoji:'🎵',title:'Səviyyə 1 Yekun Təkrarı',meta:'Ümumiləşdirmə + kiçik tamaşa',desc:'Səviyyə 1-in bütün mövzuları (əlifba, salamlaşma, ailə, bədən üzvləri, heyvanlar, rənglər, rəqəmlər, yeməklər, oyuncaqlar, təbiət) bu yekun dərsdə birləşdirilir. Uşaqlar öyrəndikləri sözlərlə kiçik bir mahnı və ya səhnəcik hazırlayır, valideynlər qarşısında nümayiş etdirir. Bu, təkcə təkrar deyil, həm də özünəinam və nitq bacarığını inkişaf etdirən yaradıcı yekundur.',words:['Təkrar: əlifba (33 hərf)','Təkrar: salamlaşma və ailə','Təkrar: bədən, heyvanlar, rənglər','Təkrar: rəqəmlər, yemək, oyuncaq, təbiət'],hw:['Öyrəndiyiniz 15 sözü seçib dəftərə yazın və mənalarını yadınıza salın.','Valideynə bu səviyyədə öyrəndiklərinizdən 5 cümlə ilə danışın.','Kiçik bir "təqdimat" hazırlayın: adınızı, ailənizi, sevimli heyvanınızı və rəngi rusca təqdim edin (5-6 cümlə).'],
 quiz:[{q:'"Привет" + "Спасибо" — bunlar nədir?',o:['Rənglər','Salamlaşma və nəzakət sözləri','Heyvanlar'],a:1},{q:'Səviyyə 1-də neçə hərf öyrəndik?',o:['26','33','30'],a:1},{q:'Səviyyə 1 neçə dərsdən ibarətdir?',o:['8','12','15'],a:2},{q:'Bu dərsin əsas məqsədi nədir?',o:['Yeni qrammatika','Bütün mövzuların təkrarı','Yeni əlifba'],a:1}]}
]},
{id:'lvl2',name:'Səviyyə 2 — Orta',lessons:[
 {id:'l16',emoji:'📅',title:'Həftənin günləri',meta:'Vaxt anlayışları',desc:'Həftənin günləri və "bu gün/sabah" kimi vaxt ifadələri, təqvim oyunu ilə.',words:['Понедельник — B.ertəsi','Среда — Çərşənbə','Пятница — Cümə','Сегодня — Bu gün','Завтра — Sabah'],hw:['Həftənin 7 gününü rusca yazın.','"Сегодня среда" kimi cümlə qurun.'],
 quiz:[{q:'"Пятница" hansı gündür?',o:['B.ertəsi','Cümə','Çərşənbə'],a:1},{q:'"Sabah" rusca necə deyilir?',o:['Сегодня','Завтра','Среда'],a:1}]},
 {id:'l17',emoji:'🏠',title:'Ev və otaqlar',meta:'Məkan sözləri',desc:'Ev daxilindəki otaqlar və əşyaların adları, "harada?" sualı ilə məşq.',words:['Кухня — Mətbəx','Спальня — Yataq otağı','Стол — Stol','Стул — Stul','Окно — Pəncərə'],hw:['Evinizin planını çəkin, otaqları rusca adlandırın.','"Где стол?" sualına cavab yazın.'],
 quiz:[{q:'"Кухня" deməkdir:',o:['Mətbəx','Yataq otağı','Pəncərə'],a:0},{q:'"Stul" rusca necə yazılır?',o:['Стол','Стул','Окно'],a:1}]},
 {id:'l18',emoji:'👕',title:'Geyimlər',meta:'Geyim adları',desc:'Köynək, şalvar, ayaqqabı kimi geyim adları, fəsillərə uyğun geyim oyunu.',words:['Рубашка — Köynək','Брюки — Şalvar','Туфли — Ayaqqabı','Шапка — Papaq','Куртка — Gödəkçə'],hw:['Geyindiyiniz əşyaları rusca yazın.','Qışda geyilən 3 geyim adını yazın.'],
 quiz:[{q:'"Туфли" nə deməkdir?',o:['Papaq','Ayaqqabı','Köynək'],a:1},{q:'"Gödəkçə" rusca necə yazılır?',o:['Куртка','Брюки','Рубашка'],a:0}]},
 {id:'l19',emoji:'🌦️',title:'Hava şəraiti',meta:'Təbiət hadisələri',desc:'Günəşli, yağışlı, qarlı kimi hava sözləri, fəsil şəkilləri ilə müzakirə.',words:['Солнце — Günəş','Дождь — Yağış','Снег — Qar','Ветер — Külək','Холодно — Soyuqdur'],hw:['Bu gün havanın necə olduğunu rusca yazın.','4 fəslin adını rusca öyrənin (əlavə resurslardan).'],
 quiz:[{q:'"Дождь" nə deməkdir?',o:['Qar','Yağış','Günəş'],a:1},{q:'"Soyuqdur" rusca necə deyilir?',o:['Холодно','Ветер','Солнце'],a:0}]},
 {id:'l20',emoji:'🔢',title:'Fellər: olmaq, etmək',meta:'Sadə qrammatika',desc:'"Mən edirəm", "sən edirsən" kimi sadə fel formaları, hərəkət şəkilləri ilə.',words:['Я делаю — Mən edirəm','Ты играешь — Sən oynayırsan','Он читает — O oxuyur','Мы идём — Biz gedirik'],hw:['"Я делаю..." ilə 2 cümlə qurun.','Bir hərəkəti rusca təsvir edin (məs. qaçmaq, oxumaq).'],
 quiz:[{q:'"Он читает" nə deməkdir?',o:['O oxuyur','O qaçır','O yatır'],a:0},{q:'"Biz gedirik" rusca necə yazılır?',o:['Мы идём','Ты играешь','Я делаю'],a:0}]},
 {id:'l21',emoji:'🏫',title:'Məktəb əşyaları',meta:'Dərs ləvazimatları',desc:'Kitab, dəftər, qələm kimi məktəb əşyalarının adları, çantanı doldurma oyunu.',words:['Книга — Kitab','Тетрадь — Dəftər','Карандаш — Qələm','Ручка — Qələm (tükənməz)','Сумка — Çanta'],hw:['Çantanızdaki əşyaları rusca sadalayın.','"Это моя книга" cümləsini yazın.'],
 quiz:[{q:'"Тетрадь" deməkdir:',o:['Kitab','Dəftər','Çanta'],a:1},{q:'"Qələm" rusca necə yazılır?',o:['Карандаш','Сумка','Книга'],a:0}]},
 {id:'l22',emoji:'⏰',title:'Saat və vaxt',meta:'Vaxt ifadə etmək',desc:'Saatı soruşmaq və cavablandırmaq, gündəlik rejim sözləri ilə.',words:['Сколько времени? — Saat neçədir?','Час — Saat','Утро — Səhər','Вечер — Axşam','Ночь — Gecə'],hw:['Öz gündəlik rejiminizi (səhər/axşam) rusca yazın.','"Сколько времени?" sualını əzbərləyin.'],
 quiz:[{q:'"Утро" nə deməkdir?',o:['Axşam','Səhər','Gecə'],a:1},{q:'"Saat neçədir?" rusca necə deyilir?',o:['Сколько времени?','Час','Ночь'],a:0}]},
 {id:'l23',emoji:'🎭',title:'Səviyyə 2 Təkrarı',meta:'Ümumiləşdirmə + dialoq',desc:'2-ci səviyyənin mövzuları üzrə cüt-cüt dialoq qurma və kiçik tamaşa.',words:['Təkrar: günlər, ev, geyim','Təkrar: hava, fellər','Təkrar: məktəb əşyaları, vaxt'],hw:['8 yeni sözü dəftərə yazın.','Dostunuzla rusca kiçik dialoq qurun (3 cümlə).'],
 quiz:[{q:'Səviyyə 2-də neçə yeni mövzu öyrəndik?',o:['3','7','15'],a:1},{q:'"Мы идём" hansı mövzuya aiddir?',o:['Fellər','Rənglər','Heyvanlar'],a:0}]}
]},
{id:'lvl3',name:'Səviyyə 3 — İrəliləmiş',lessons:[
 {id:'l24',emoji:'💬',title:'Sadə dialoqlar',meta:'Danışıq vərdişləri',desc:'Restoranda, mağazada sadə dialoq qurma, rollu oyunlarla canlandırma.',words:['Сколько это стоит? — Bu neçəyədir?','Я хочу... — Mən istəyirəm...','Дайте, пожалуйста — Verin, lütfən','Хорошо — Yaxşı'],hw:['Mağazada alış-veriş dialoqu yazın (4 cümlə).','"Я хочу..." ilə 3 cümlə qurun.'],
 quiz:[{q:'"Сколько это стоит?" nə deməkdir?',o:['Bu neçəyədir?','Bu nədir?','Hara gedirsən?'],a:0},{q:'"Lütfən" rusca necə deyilir?',o:['Хорошо','Пожалуйста','Дайте'],a:1}]},
 {id:'l25',emoji:'🧩',title:'Sifətlər',meta:'Təsvir sözləri',desc:'Böyük, kiçik, gözəl, yaxşı kimi sifətlər, əşyaları təsvir etmə oyunu.',words:['Большой — Böyük','Маленький — Kiçik','Красивый — Gözəl','Хороший — Yaxşı','Плохой — Pis'],hw:['3 əşyanı sifətlərlə təsvir edin.','"Это большой дом" kimi cümlə qurun.'],
 quiz:[{q:'"Маленький" deməkdir:',o:['Böyük','Kiçik','Gözəl'],a:1},{q:'"Pis" rusca necə yazılır?',o:['Хороший','Плохой','Красивый'],a:1}]},
 {id:'l26',emoji:'📖',title:'Qısa hekayə',meta:'Oxu vərdişi',desc:'Sadə qısa hekayə oxuma və başa düşmə, şəkilli kitabçalarla.',words:['Однажды — Bir gün','Жил-был — Yaşayırdı','Конец — Son','Сказка — Nağıl'],hw:['Hekayəni oxuyub 2 sual yazın.','Öz qısa hekayənizi (3 cümlə) rusca yazmağa cəhd edin.'],
 quiz:[{q:'"Сказка" nə deməkdir?',o:['Nağıl','Son','Bir gün'],a:0},{q:'"Жил-был" hansı mənada işlənir?',o:['Bir gün yaşayırdı','Salam','Sağ ol'],a:0}]},
 {id:'l27',emoji:'🗣️',title:'Sual cümlələri',meta:'Sual qurma',desc:'Kim, nə, harada, niyə kimi sual sözləri ilə cümlə qurma.',words:['Кто? — Kim?','Что? — Nə?','Где? — Harada?','Почему? — Niyə?','Когда? — Nə vaxt?'],hw:['5 sual sözü ilə 5 sual yazın.','Dostunuza rusca 2 sual verin.'],
 quiz:[{q:'"Почему?" deməkdir:',o:['Niyə?','Kim?','Harada?'],a:0},{q:'"Nə vaxt?" rusca necə deyilir?',o:['Кто?','Когда?','Что?'],a:1}]},
 {id:'l28',emoji:'🌍',title:'Şəhər və nəqliyyat',meta:'Gündəlik həyat',desc:'Avtobus, maşın, küçə kimi şəhər və nəqliyyat sözləri.',words:['Город — Şəhər','Улица — Küçə','Автобус — Avtobus','Машина — Maşın','Метро — Metro'],hw:['Şəhərinizdə gördüyünüz nəqliyyatı rusca yazın.','"Я еду на автобусе" cümləsini yazın.'],
 quiz:[{q:'"Улица" nə deməkdir?',o:['Şəhər','Küçə','Metro'],a:1},{q:'"Maşın" rusca necə yazılır?',o:['Машина','Автобус','Город'],a:0}]},
 {id:'l29',emoji:'🎉',title:'Bayramlar',meta:'Mədəniyyət',desc:'Ad günü, Yeni il kimi bayram sözləri, təbrik ifadələri ilə.',words:['День рождения — Ad günü','Новый год — Yeni il','Поздравляю! — Təbrik edirəm!','Праздник — Bayram'],hw:['Bir bayramı rusca təbrik edin (1 cümlə).','Sevimli bayramınızı rusca yazın.'],
 quiz:[{q:'"Поздравляю!" deməkdir:',o:['Sağ ol','Təbrik edirəm!','Bağışla'],a:1},{q:'"Yeni il" rusca necə yazılır?',o:['Новый год','Праздник','День рождения'],a:0}]},
 {id:'l30',emoji:'🧠',title:'Qarışıq möhkəmləndirmə',meta:'Bütün mövzular',desc:'Bütün öyrənilən mövzulardan qarışıq tapşırıqlar və komanda oyunları.',words:['Bütün mövzuların təkrarı','Komanda yarışı','Sürətli cavab oyunu'],hw:['10 sual özünüz üçün yazıb cavablandırın.','Ən çətin hesab etdiyiniz 3 sözü təkrar edin.'],
 quiz:[{q:'Bu dərs nəyə həsr olunub?',o:['Yeni hərflər','Ümumi təkrar','Yeni rənglər'],a:1},{q:'24 dərsdən neçəsini bitirdik (bu dərslə)?',o:['20','23','24'],a:1}]},
 {id:'l31',emoji:'🏆',title:'Yekun: Bitirmə Dərsi',meta:'Final qiymətləndirməsi',desc:'Proqramın yekun dərsi — bütün biliklərin yoxlanılması və sertifikat təqdimatı.',words:['Поздравляю с окончанием! — Bitirməyiniz münasibətilə təbrik!','Молодец! — Əhsən!'],hw:['Proqram boyu öyrəndiyiniz 15 sözü siyahı şəklində yazın.','Valideynlərinizlə öyrəndiklərinizi nümayiş etdirin.'],
 quiz:[{q:'"Молодец!" nə deməkdir?',o:['Əhsən!','Sağol','Niyə?'],a:0},{q:'Proqram neçə dərsdən ibarətdir?',o:['12','18','24'],a:2}]}
]},
{id:'lvl4',name:'10-12 yaş — Dərin Qrammatika (rus dilində)',lessons:[
 {id:'l32',emoji:'📘',title:'Имя существительное: Род',meta:'Существительное и его род',desc:'Существительные в русском языке делятся на три рода: мужской, женский и средний. Род определяется по окончанию слова. Например: стол (м.р.), книга (ж.р.), окно (ср.р.).',words:['Стол (м.р.) — Stol','Книга (ж.р.) — Kitab','Окно (ср.р.) — Pəncərə','Учитель (м.р.) — Müəllim','Тетрадь (ж.р.) — Dəftər'],hw:['Найдите 5 слов мужского рода и 5 слов женского рода.','Определите род слов: яблоко, машина, дом.'],
 quiz:[{q:'Какого рода слово "книга"?',o:['Мужской','Женский','Средний'],a:1},{q:'Слово "окно" — это:',o:['Мужской род','Женский род','Средний род'],a:2}]},
 {id:'l33',emoji:'❓',title:'Падежи: Именительный и Винительный',meta:'Падежная система',desc:'Именительный падеж отвечает на вопрос «кто? что?» — это подлежащее. Винительный падеж отвечает на вопрос «кого? что?» — это прямое дополнение. Пример: Это стол (им.). Я вижу книгу (вин.).',words:['Кто? Что? — İmenitelnı sual','Кого? Что? — Vinitelnı sual','Я вижу книгу — Mən kitabı görürəm','Это стол — Bu stoldur'],hw:['Составьте 3 предложения в винительном падеже.','Подчеркните подлежащее в 3 предложениях из учебника.'],
 quiz:[{q:'На какой вопрос отвечает именительный падеж?',o:['Кто? Что?','Кого? Чего?','Где?'],a:0},{q:'"Я вижу книгу" — слово "книгу" в каком падеже?',o:['Именительный','Винительный','Родительный'],a:1}]},
 {id:'l34',emoji:'🏠',title:'Родительный падеж',meta:'Принадлежность',desc:'Родительный падеж отвечает на вопрос «кого? чего?» и часто обозначает принадлежность: дом отца, книга друга.',words:['Кого? Чего? — sual','Дом отца — Atanın evi','Книга друга — Dostun kitabı','Нет воды — Su yoxdur'],hw:['Составьте 3 словосочетания в родительном падеже.','Переведите на русский: "atanın maşını".'],
 quiz:[{q:'Родительный падеж отвечает на вопрос:',o:['Кто? Что?','Кого? Чего?','Куда?'],a:1},{q:'"Дом отца" показывает:',o:['Действие','Принадлежность','Цвет'],a:1}]},
 {id:'l35',emoji:'⏳',title:'Глагол: Настоящее время',meta:'Спряжение глаголов',desc:'Глаголы в настоящем времени изменяются по лицам и числам: я делаю, ты делаешь, он делает, мы делаем, они делают.',words:['Я делаю — Mən edirəm','Ты играешь — Sən oynayırsan','Он читает — O oxuyur','Мы говорим — Biz danışırıq','Они идут — Onlar gedirlər'],hw:['Проспрягайте глагол "играть" по всем лицам.','Составьте 3 предложения в настоящем времени.'],
 quiz:[{q:'"Они идут" — это какое время?',o:['Прошедшее','Настоящее','Будущее'],a:1},{q:'Глагол "делать" в форме "ты":',o:['Делаю','Делаешь','Делает'],a:1}]},
 {id:'l36',emoji:'⏰',title:'Глагол: Прошедшее и будущее',meta:'Времена глагола',desc:'Прошедшее время образуется с суффиксом -л: играл, читала. Будущее время — с глаголом «быть» или приставкой: будем играть, сыграет.',words:['Я играл — Mən oynadım','Она читала — O oxudu','Мы будем играть — Biz oynayacağıq','Он сыграет — O oynayacaq'],hw:['Напишите 3 предложения в прошедшем времени.','Напишите 3 предложения в будущем времени.'],
 quiz:[{q:'"Она читала" — какое время?',o:['Настоящее','Прошедшее','Будущее'],a:1},{q:'Будущее время глагола "играть" с "мы":',o:['Играли','Играем','Будем играть'],a:2}]},
 {id:'l37',emoji:'🎨',title:'Прилагательное: согласование',meta:'Согласование с существительным',desc:'Прилагательное согласуется с существительным в роде, числе и падеже: большой дом, большая книга, большое окно, большие дома.',words:['Большой дом — böyük ev','Большая книга — böyük kitab','Большое окно — böyük pəncərə','Красивые цветы — gözəl çiçəklər'],hw:['Подберите прилагательные к 5 существительным разного рода.','Составьте 3 словосочетания "прилагательное+существительное".'],
 quiz:[{q:'"Большая" сочетается со словом:',o:['Дом','Книга','Окно'],a:1},{q:'Прилагательное согласуется с существительным в:',o:['Цвете','Роде, числе, падеже','Времени'],a:1}]},
 {id:'l38',emoji:'🔢',title:'Числительные',meta:'Количественные и порядковые',desc:'Количественные числительные отвечают на вопрос «сколько?» (один, два, три), порядковые — «который?» (первый, второй, третий).',words:['Один, два, три — say','Первый, второй, третий — sıra','Сколько? — neçə?','Который? — neçənci?'],hw:['Напишите числа от 1 до 20 по-русски.','Напишите порядковые числительные от 1 до 10.'],
 quiz:[{q:'"Третий" — это числительное:',o:['Количественное','Порядковое'],a:1},{q:'"Сколько?" задаётся к числительному:',o:['Количественному','Порядковому'],a:0}]},
 {id:'l39',emoji:'📍',title:'Предлоги места и времени',meta:'Предлоги',desc:'Предлоги «в, на, под, за, через, после» показывают место или время действия: в школе, на столе, под столом, после урока, через час.',words:['В школе — məktəbdə','На столе — stolun üstündə','Под столом — stolun altında','После урока — dərsdən sonra','Через час — bir saatdan sonra'],hw:['Составьте 5 предложений с разными предлогами.','Подчеркните предлоги в тексте учебника.'],
 quiz:[{q:'"После урока" показывает:',o:['Место','Время','Цвет'],a:1},{q:'"Под столом" — какой предлог?',o:['На','Под','После'],a:1}]},
 {id:'l40',emoji:'🔗',title:'Сложное предложение',meta:'Союзы',desc:'Союзы «и, а, но, потому что» соединяют простые предложения в сложные: Я читаю, а он играет. Я устал, потому что много работал.',words:['И — və','А — amma','Но — lakin','Потому что — çünki'],hw:['Составьте 3 сложных предложения с союзами.','Найдите союзы в тексте учебника.'],
 quiz:[{q:'Союз "потому что" выражает:',o:['Причину','Время','Место'],a:0},{q:'"Я читаю, а он играет" — союз:',o:['И','А','Но'],a:1}]},
 {id:'l41',emoji:'🏆',title:'Итоговый урок',meta:'Повторение и сочинение',desc:'Итоговый урок — повторение всей грамматики: род, падежи, время глагола, прилагательные, числительные, предлоги, союзы. Напишите небольшое сочинение, используя изученные правила.',words:['Повторение — təkrar','Сочинение — inşa','Грамматика — qrammatika'],hw:['Напишите сочинение из 5-6 предложений на тему "Моя семья".','Используйте минимум 3 разных падежа в сочинении.'],
 quiz:[{q:'Сколько падежей вы изучили в этом блоке?',o:['1','3','6'],a:1},{q:'Итоговое задание — это:',o:['Тест','Сочинение','Игра'],a:1}]}
]}
];

/* =========================================================
   ADULT_LEVELS — Yeniyetmə/Böyük proqramı
   CEFR (Avropa Şurası Dil Çərçivəsi) əsasında: A1 → B2
   Faza 2: yalnız A1 hazırdır. A2/B1/B2 növbəti fazalarda əlavə olunacaq.
   ========================================================= */
const ADULT_LEVELS = [
{id:'a1',name:'A1 — Başlanğıc (CEFR)',lessons:[
 {id:'a1-1',emoji:'🤝',title:'Tanışlıq',meta:'Знакомство · CEFR A1.1',desc:'Rus dilində özünü təqdim etmək, ad soruşmaq və cavab vermək. "Здравствуйте" rəsmi, "Привет" qeyri-rəsmi salamlaşmadır — hansını nə vaxt işlətmək lazım olduğunu öyrənirik.',words:['Здравствуйте — Salam (rəsmi)','Меня зовут... — Mənim adım...','Как вас зовут? — Sizin adınız nədir?','Очень приятно — Çox şadam','Я из Азербайджана — Mən Azərbaycandanam'],hw:['Özünüzü rusca 4 cümlə ilə təqdim edin (ad, ölkə, şəhər, peşə).','Rəsmi və qeyri-rəsmi salamlaşmanı bir cədvəldə müqayisə edin.'],
 quiz:[{q:'"Меня зовут..." nə deməkdir?',o:['Mənim adım...','Sizin adınız...','Mən yaşayıram...'],a:0},{q:'Hansı forma rəsmidir?',o:['Привет','Здравствуйте','Пока'],a:1}]},
 {id:'a1-2',emoji:'🔤',title:'Fonetika: Sait və samitlər',meta:'Произношение · CEFR A1.1',desc:'Rus dilinin tələffüz qaydaları: vurğu (ударение) sözün mənasını dəyişə bilər (замок — qala / зáмок — kilid). Yumşaq (ь) və sərt işarələr (ъ) samitlərin səsini dəyişir.',words:['Замок — qala (vurğu 2-ci hecada)','Зáмок — kilid (vurğu 1-ci hecada)','Мать — ana (yumşaq т)','Съезд — qurultay (ъ ilə ayrılma)','Ударение — vurğu'],hw:['5 sözdə vurğunun yerini işarələyin (lüğətdən).','Web Speech səsləndirmə ilə 10 sözü dinləyib təkrarlayın.'],
 quiz:[{q:'Rus dilində vurğu sözün mənasını:',o:['Heç vaxt dəyişmir','Dəyişə bilər','Yalnız yazıda dəyişir'],a:1},{q:'"Ь" işarəsi nəyi bildirir?',o:['Sərtlik','Yumşaqlıq','Uzunluq'],a:1}]},
 {id:'a1-3',emoji:'🧍',title:'Fe\'l "быть" və şəxs əvəzlikləri',meta:'Глагол "быть" · CEFR A1.1',desc:'"Быть" (olmaq) feli rus dilində indiki zamanda adətən buraxılır: "Я студент" (Mən tələbəyəm) — "являюсь" deyilmir. Şəxs əvəzlikləri: я, ты, он/она, мы, вы, они.',words:['Я — Mən','Ты — Sən','Он / Она — O (kişi/qadın)','Мы — Biz','Вы — Siz','Они — Onlar'],hw:['6 şəxs əvəzliyi ilə 6 cümlə qurun ("Я студент", "Он врач" kimi).','"Кто вы?" sualına öz peşənizlə cavab yazın.'],
 quiz:[{q:'"Я студент" cümləsində "являюсь" (olmaq feli) niyə yoxdur?',o:['Səhvdir','İndiki zamanda buraxılır','Yalnız kitab dilində olur'],a:1},{q:'"Она" hansı əvəzlikdir?',o:['Mən','O (qadın)','Siz'],a:1}]},
 {id:'a1-4',emoji:'📇',title:'İsmin cinsi',meta:'Род существительных · CEFR A1.2',desc:'Rus isimlərinin 3 cinsi var: kişi (мужской — samitlə bitir: стол), qadın (женский — -а/-я ilə bitir: книга), orta (средний — -о/-е ilə bitir: окно). Cinsi bilmək sifət və fel uzlaşması üçün vacibdir.',words:['Стол (м.р.) — Stol','Книга (ж.р.) — Kitab','Окно (ср.р.) — Pəncərə','Учитель (м.р.) — Müəllim','Дверь (ж.р., istisna) — Qapı'],hw:['10 yeni sözün cinsini müəyyən edin (lüğətdən seçin).','3 istisna sözü tapıb yazın (yumşaq işarə ilə bitən qadın cinsi sözlər).'],
 quiz:[{q:'"-а" ilə bitən söz adətən hansı cinsdəndir?',o:['Kişi','Qadın','Orta'],a:1},{q:'"Окно" hansı cinsdəndir?',o:['Kişi','Qadın','Orta'],a:2}]},
 {id:'a1-5',emoji:'🔢',title:'Rəqəmlər və qiymətlər',meta:'Числительные · CEFR A1.2',desc:'1-100 arası rəqəmlər və qiymət soruşmaq: "Сколько стоит?" (Neçəyədir?). Rus dilində rəqəmdən sonra isim forması dəyişir (1 rubl, 2 rublya, 5 rubley) — bu, A2-də dərinləşdiriləcək.',words:['Один, два, три... десять — 1-10','Двадцать, тридцать — 20, 30','Сто — 100','Сколько стоит? — Neçəyədir?','Это стоит 10 манат — Bu 10 manatdır'],hw:['1-100 arası 15 rəqəmi rusca yazın.','Mağazada 3 əşyanın qiymətini soruşan dialoq qurun.'],
 quiz:[{q:'"Сколько стоит?" nə deməkdir?',o:['Neçəyədir?','Neçə yaşındasan?','Saat neçədir?'],a:0},{q:'"100" rusca necə yazılır?',o:['Десять','Сто','Тридцать'],a:1}]},
 {id:'a1-6',emoji:'👔',title:'Peşələr və iş',meta:'Профессии · CEFR A1.2',desc:'Əsas peşə adları və "Kim işləyirsiniz?" sualı: "Кем вы работаете?" — cavab isə Творительный падeж (yaradıcı hal) ilə verilir: "Я работаю врачом" (Mən həkim işləyirəm).',words:['Врач — Həkim','Учитель — Müəllim','Инженер — Mühəndis','Программист — Proqramçı','Кем вы работаете? — Kim işləyirsiniz?'],hw:['Öz peşənizi "Я работаю..." forması ilə yazın.','5 peşə adını rusca-azərbaycanca lüğətə əlavə edin.'],
 quiz:[{q:'"Кем вы работаете?" sualının mənası:',o:['Harada yaşayırsınız?','Kim işləyirsiniz?','Neçə yaşındasınız?'],a:1},{q:'"Я работаю врачом" — "врачом" hansı halda?',o:['İmenitelnı','Yaradıcı (Творительный)','Vinitelnı'],a:1}]},
 {id:'a1-7',emoji:'🛒',title:'Mağazada / Alış-veriş',meta:'В магазине · CEFR A1.3',desc:'Mağazada real dialoq: nə istədiyini demək, qiymət soruşmaq, "Dayте, пожалуйста" ilə xahiş etmək. Bu dərs tam dialoq simulyasiyası ilə işlənir.',words:['Дайте, пожалуйста — Verin, lütfən','У вас есть...? — Sizdə var mı...?','Я возьму это — Mən bunu götürəcəm','Наличными или картой? — Nəğd yoxsa kartla?','Вот, пожалуйста — Buyurun'],hw:['Mağazada tam dialoq yazın (6-8 replika).','"У вас есть...?" ilə 3 sual qurun.'],
 quiz:[{q:'"Наличными или картой?" nə soruşur?',o:['Ödəniş üsulunu','Ünvanı','Qiyməti'],a:0},{q:'"Дайте, пожалуйста" hansı funksiyanı daşıyır?',o:['Salamlaşma','Nəzakətli xahiş','Vidalaşma'],a:1}]},
 {id:'a1-8',emoji:'🍽️',title:'Restoranda',meta:'В ресторане · CEFR A1.3',desc:'Restoranda sifariş vermək, menyu haqqında sual vermək, hesab istəmək. "Я хотел(а) бы..." — nəzakətli istək forması ("Я хочу" daha sərtdir).',words:['Я хотел(а) бы... — İstərdim ki...','Меню, пожалуйста — Menyu, lütfən','Что вы порекомендуете? — Nə tövsiyə edərsiniz?','Счёт, пожалуйста — Hesab, lütfən','Приятного аппетита! — Nuş olsun!'],hw:['Restoranda sifariş dialoqu yazın (5 replika).','"Я хотел(а) бы..." ilə 3 nəzakətli istək cümləsi qurun.'],
 quiz:[{q:'"Я хотел бы" ilə "Я хочу" arasındakı fərq:',o:['Fərq yoxdur','Birinci daha nəzakətlidir','İkinci daha nəzakətlidir'],a:1},{q:'"Счёт, пожалуйста" nə deməkdir?',o:['Menyu, lütfən','Hesab, lütfən','Su, lütfən'],a:1}]},
 {id:'a1-9',emoji:'🧭',title:'Şəhərdə istiqamət',meta:'В городе · CEFR A1.3',desc:'Yol soruşmaq və istiqamət göstərmək: налево (sola), направо (sağa), прямо (düz). "Как пройти..." — piyada gedərkən, "Как проехать..." — nəqliyyatla gedərkən işlənir.',words:['Как пройти до...? — ...necə getmək olar (piyada)','Налево — Sola','Направо — Sağa','Прямо — Düz','Это далеко? — Bu uzaqdır?'],hw:['Öz məhəllənizdən mərkəzə yol təsviri yazın (rusca).','Xəritə üzərində 3 istiqamət cümləsi qurun.'],
 quiz:[{q:'"Направо" nə deməkdir?',o:['Sola','Sağa','Düz'],a:1},{q:'"Как пройти" hansı halda işlənir?',o:['Nəqliyyatla','Piyada','Təyyarə ilə'],a:1}]},
 {id:'a1-10',emoji:'📆',title:'Gündəlik rutin',meta:'Распорядок дня · CEFR A1.4',desc:'Gündəlik hərəkətləri təsvir etmək üçün indiki zaman fellərinin şəxslərə görə dəyişməsi: вставать (durmaq), завтракать (səhər yeməyi yemək), работать (işləmək) və s. Refleksiv fellər (-ся) ilə tanışlıq.',words:['Я встаю в 7 часов — Mən saat 7-də dururam','Я завтракаю — Mən səhər yeməyi yeyirəm','Я иду на работу — Mən işə gedirəm','Я ложусь спать — Mən yatmağa gedirəm (-ся feli)'],hw:['Öz gündəlik rejiminizi 6 cümlə ilə rusca yazın.','-ся ilə bitən 3 fel tapıb mənasını yazın.'],
 quiz:[{q:'"-ся" şəkilçisi felə nə əlavə edir?',o:['Keçmiş zaman mənası','Refleksivlik (özünə yönəlmə)','Cəm mənası'],a:1},{q:'"Я иду на работу" nə deməkdir?',o:['Mən evə gedirəm','Mən işə gedirəm','Mən yatıram'],a:1}]},
 {id:'a1-11',emoji:'🌦️',title:'Hava və fəsillər',meta:'Погода и времена года · CEFR A1.4',desc:'Hava haqqında danışmaq üçün şəxssiz cümlələr: "На улице холодно" (Küçədə soyuqdur) — burada fail yoxdur, bu, rus dilinə xas bir quruluşdur.',words:['На улице холодно — Küçədə soyuqdur','Идёт дождь — Yağış yağır','Сегодня солнечно — Bu gün günəşlidir','Зимой холодно, летом жарко — Qışda soyuq, yayda isti'],hw:['4 fəsli hava şəraiti ilə təsvir edən 4 cümlə yazın.','"Идёт дождь/снег" strukturunu izah edin.'],
 quiz:[{q:'"На улице холодно" cümləsində fail (kim?) varmı?',o:['Bəli, "улица"','Xeyr, şəxssiz cümlədir','Bəli, gizli "я"'],a:1},{q:'"Идёт дождь" hərfi mənası:',o:['Yağış gedir','Yağış yağır','Yağış dayanır'],a:1}]},
 {id:'a1-12',emoji:'🏆',title:'A1 Yekun: Özünütəqdimat və keçid testi',meta:'Итоговый тест A1 · CEFR A1 → A2',desc:'A1 səviyyəsinin bütün mövzularını birləşdirən yekun tapşırıq: tam özünütəqdimat mətni (ad, peşə, ailə, gündəlik rejim, hava) yazmaq və A2 səviyyəsinə keçid testi.',words:['Итог — Yekun','Переход на уровень А2 — A2 səviyyəsinə keçid','Поздравляем! — Təbrik edirik!'],hw:['8-10 cümləlik tam özünütəqdimat mətni yazın (bütün A1 mövzularından istifadə edərək).','Öyrəndiyiniz 30 sözü təkrarlayıb özünüzü yoxlayın.'],
 quiz:[{q:'A1 səviyyəsində neçə əsas mövzu keçdik?',o:['6','12','20'],a:1},{q:'A1-dən sonra hansı səviyyəyə keçilir?',o:['B1','A2','B2'],a:1}]}
]},
{id:'a2',name:'A2 — Elementar (CEFR)',lessons:[
 {id:'a2-1',emoji:'⏳',title:'Keçmiş zaman',meta:'Прошедшее время · CEFR A2.1',desc:'Rus dilində keçmiş zaman fe\'lin cinsinə görə dəyişir (indiki zamandan fərqli olaraq şəxsə görə yox!): я/ты/он читал, я/ты/она читала, оно читало, мы/вы/они читали. Fe\'lin cinsi mübtədanın cinsinə uyğunlaşır.',words:['Он читал — O oxudu (kişi)','Она читала — O oxudu (qadın)','Оно было — O idi (orta cins)','Мы говорили — Biz danışdıq','Вчера — Dünən'],hw:['5 fe\'li keçmiş zamanda kişi/qadın/cəm formasında yazın.','"Вчера я..." ilə 3 cümlə qurun.'],
 quiz:[{q:'Keçmiş zamanda fe\'l nəyə görə dəyişir?',o:['Şəxsə görə','Cins və sayına görə','Heç nəyə görə'],a:1},{q:'"Она читала" — bu forma hansı cinsə aiddir?',o:['Kişi','Qadın','Orta'],a:1}]},
 {id:'a2-2',emoji:'🔮',title:'Gələcək zaman',meta:'Будущее время · CEFR A2.1',desc:'Rus dilində gələcək zamanın 2 forması var: mürəkkəb (буду + məsdər — несовершенный fe\'llə: буду читать) və sadə (совершенный fe\'lin şəxs forması: прочитаю). Fərq: birincisi davamlı hərəkət, ikincisi tamamlanmış hərəkət bildirir.',words:['Я буду читать — Mən oxuyacağam (davamlı)','Я прочитаю — Mən oxuyub bitirəcəyəm','Завтра — Sabah','Мы будем работать — Biz işləyəcəyik'],hw:['Hər iki gələcək zaman formasında 2-şər cümlə qurun.','Fərqi öz sözlərinizlə izah edin.'],
 quiz:[{q:'"Буду читать" hansı formadır?',o:['Sadə gələcək','Mürəkkəb gələcək','Keçmiş zaman'],a:1},{q:'"Прочитаю" nəyi bildirir?',o:['Davamlı hərəkəti','Tamamlanmış hərəkəti','Keçmişi'],a:1}]},
 {id:'a2-3',emoji:'🔁',title:'Fe\'lin görünüşü: несовершенный/совершенный',meta:'Вид глагола · CEFR A2.1',desc:'Bu, rus qrammatikasının ən vacib mövzularından biridir. Несовершенный (qeyri-kamil) görünüş — hərəkətin prosesini bildirir (делать — etmək). Совершенный (kamil) görünüş — hərəkətin nəticəsini/bitməsini bildirir (сделать — edib qurtarmaq). Əksər fe\'llər cüt şəklində olur: читать/прочитать, писать/написать.',words:['Делать (несов.) — etmək (proses)','Сделать (сов.) — edib qurtarmaq','Читать / Прочитать — oxumaq / oxuyub bitirmək','Писать / Написать — yazmaq / yazıb bitirmək'],hw:['5 fe\'l cütünü (несов./сов.) tapıb yazın.','Hər cütdən nümunə cümlə qurun.'],
 quiz:[{q:'"Прочитать" hansı görünüşdür?',o:['Несовершенный','Совершенный'],a:1},{q:'Несовершенный fe\'l nəyi bildirir?',o:['Hərəkətin prosesini','Hərəkətin nəticəsini','Yalnız keçmişi'],a:0}]},
 {id:'a2-4',emoji:'🎁',title:'Дательный падеж',meta:'Verilmə halı · CEFR A2.2',desc:'Дательный падеж (verilmə halı) «kimə? nəyə?» sualına cavab verir və adətən kiməsə bir şey vermək/demək/göstərmək mənasında işlənir: Я дал книгу другу (Mən dosta kitab verdim). Həmçinin yaş bildirmək üçün işlənir: Мне 20 лет (Mən 20 yaşındayam).',words:['Кому? Чему? — Kimə? Nəyə?','Я дал другу — Mən dosta verdim','Мне 20 лет — Mən 20 yaşındayam','Я звоню маме — Mən anama zəng edirəm'],hw:['3 cümlə "kiməsə nəsə vermək/demək" mənasında dательный падeж ilə qurun.','Öz yaşınızı rusca yazın (Мне ... лет).'],
 quiz:[{q:'Дательный падеж hansı suala cavab verir?',o:['Kim? Nə?','Kimə? Nəyə?','Harada?'],a:1},{q:'"Мне 20 лет" quruluşu:',o:['Adi cümlə','Дательный падeж ilə yaş','Keçmiş zaman'],a:1}]},
 {id:'a2-5',emoji:'🔧',title:'Творительный падеж',meta:'Yaradıcı hal (dərinləşdirmə) · CEFR A2.2',desc:'Творительный падеж «nə ilə? kiminlə?» sualına cavab verir — alət, birgəlik və peşə bildirir: Я пишу ручкой (Mən qələmlə yazıram), Я иду с другом (Mən dostla gedirəm), Он работает врачом (O həkim işləyir).',words:['Чем? С кем? — Nə ilə? Kiminlə?','Я пишу ручкой — Mən qələmlə yazıram','Я иду с другом — Mən dostla gedirəm','Он работает врачом — O həkim işləyir'],hw:['"Alət ilə" mənasında 3 cümlə qurun (ручкой, ножом, ложкой).','"С кем вы идёте?" sualına cavab yazın.'],
 quiz:[{q:'Творительный падeж hansı suala cavab verir?',o:['Nə ilə? Kiminlə?','Kimə?','Haradan?'],a:0},{q:'"Я пишу ручкой" — "ручкой" nəyi bildirir?',o:['Yeri','Aləti','Zamanı'],a:1}]},
 {id:'a2-6',emoji:'💭',title:'Предложный падеж',meta:'Yerlik hal · CEFR A2.2',desc:'Предложный падeж yalnız «в» və «на» ön qoşmaları ilə işlənir, «harada?» və «nə haqqında?» suallarına cavab verir: Я живу в Баку (Mən Bakıda yaşayıram), Я думаю о тебе (Mən sənin haqqında düşünürəm).',words:['Где? О чём? — Harada? Nə haqqında?','Я живу в Баку — Mən Bakıda yaşayıram','Я думаю о тебе — Mən sənin haqqında düşünürəm','В школе — Məktəbdə'],hw:['3 cümlə "harada?" mənasında предложный падeж ilə qurun.','"О чём вы думаете?" sualına cavab yazın.'],
 quiz:[{q:'Предложный падeж yalnız hansı ön qoşmalarla işlənir?',o:['У, от','В, на','К, по'],a:1},{q:'"Я живу в Баку" — "в Баку" hansı haldadır?',o:['Дательный','Предложный','Творительный'],a:1}]},
 {id:'a2-7',emoji:'✅',title:'Modal fellər: можно, нужно, хочу',meta:'Модальные глаголы · CEFR A2.3',desc:'Modal fellər icazə, ehtiyac və istəyi bildirir: можно (olar), нужно (lazımdır), хочу (istəyirəm), могу (bilirəm/bacarıram). Bu fellər əsasən şəxssiz və ya "я" ilə işlənir: Мне нужно идти (Mən getməliyəm).',words:['Можно? — Olar mı?','Мне нужно... — Mənə lazımdır ki...','Я хочу... — Mən istəyirəm...','Я могу... — Mən bilirəm/bacarıram...'],hw:['4 modal felin hər biri ilə cümlə qurun.','"Можно?" ilə nəzakətli icazə sualı yazın.'],
 quiz:[{q:'"Мне нужно идти" nə deməkdir?',o:['Mən getmək istəyirəm','Mən getməliyəm','Mən gedə bilərəm'],a:1},{q:'"Можно?" hansı mənanı verir?',o:['Lazımdır?','Olar mı?','İstəyirsən?'],a:1}]},
 {id:'a2-8',emoji:'📊',title:'Sifətin dərəcələri',meta:'Степени сравнения · CEFR A2.3',desc:'Müqayisə dərəcəsi (сравнительная степень) -ее/-ей şəkilçisi ilə düzəlir: красивый → красивее (gözəl → daha gözəl). Üstünlük dərəcəsi (превосходная степень) «самый» sözü ilə: самый красивый (ən gözəl).',words:['Красивый — Gözəl','Красивее — Daha gözəl','Самый красивый — Ən gözəl','Лучше — Daha yaxşı (istisna)','Хуже — Daha pis (istisna)'],hw:['5 sifəti müqayisə dərəcəsinə salın.','"Самый..." ilə 2 cümlə qurun.'],
 quiz:[{q:'"Красивее" hansı dərəcədir?',o:['Adi','Müqayisə','Üstünlük'],a:1},{q:'Üstünlük dərəcəsi hansı sözlə düzəlir?',o:['Более','Самый','Очень'],a:1}]},
 {id:'a2-9',emoji:'📞',title:'Telefon danışığı',meta:'Телефонный разговор · CEFR A2.3',desc:'Telefonla rəsmi və qeyri-rəsmi danışıq qəlibləri: Алло, кто это? (Alo, kimdir?), Можно попросить...? (...ı çağırmaq olar mı?), Перезвоните, пожалуйста (Zəhmət olmasa yenidən zəng edin).',words:['Алло! — Alo!','Можно попросить...? — ...ı istəmək olar?','Одну минуту — Bir dəqiqə','Перезвоните позже — Sonra yenidən zəng edin'],hw:['Telefon dialoqu yazın (6 replika, iş ilə bağlı).','"Можно попросить...?" ilə 2 cümlə qurun.'],
 quiz:[{q:'"Одну минуту" nə deməkdir?',o:['Bir saat','Bir dəqiqə','Bir gün'],a:1},{q:'"Перезвоните позже" nəyi xahiş edir?',o:['İndi zəng etməyi','Sonra yenidən zəng etməyi','Zəng etməməyi'],a:1}]},
 {id:'a2-10',emoji:'🏥',title:'Həkimdə / Səhhət',meta:'У врача · CEFR A2.4',desc:'Səhhətlə bağlı əsas ifadələr: у меня болит... (mənim ... ağrıyır), simptomları təsvir etmək, dərman haqqında sual vermək. Bədən üzvləri Дательный падeж ilə "у меня" quruluşunda işlənir.',words:['У меня болит голова — Başım ağrıyır','У меня температура — Hərarətim var','Мне нужен врач — Mənə həkim lazımdır','Аптека — Aptek'],hw:['3 simptomu rusca təsvir edin ("У меня болит...").','Aptekdə dərman istəyən dialoq yazın.'],
 quiz:[{q:'"У меня болит голова" nə deməkdir?',o:['Başım ağrıyır','Mədəm ağrıyır','Hərarətim var'],a:0},{q:'"Аптека" nə deməkdir?',o:['Xəstəxana','Aptek','Həkim'],a:1}]},
 {id:'a2-11',emoji:'✈️',title:'Səyahət və bilet almaq',meta:'Путешествие · CEFR A2.4',desc:'Bilet almaq, aeroportda/vağzalda danışmaq: Один билет до Москвы (Moskvaya bir bilet), туда и обратно (gediş-qayıdış), во сколько вылет? (uçuş neçədə?).',words:['Один билет до... — ...-a bir bilet','Туда и обратно — Gediş-qayıdış','Во сколько вылет? — Uçuş neçədə?','Паспорт, пожалуйста — Pasport, lütfən'],hw:['Aeroportda bilet alma dialoqu yazın (5 replika).','"Во сколько...?" ilə 2 sual qurun.'],
 quiz:[{q:'"Туда и обратно" nə deməkdir?',o:['Yalnız gediş','Gediş-qayıdış','Yalnız qayıdış'],a:1},{q:'"Во сколько вылет?" nəyi soruşur?',o:['Qiyməti','Uçuş vaxtını','Ünvanı'],a:1}]},
 {id:'a2-12',emoji:'🏆',title:'A2 Yekun: Sərbəst mətn və keçid testi',meta:'Итоговый тест A2 · CEFR A2 → B1',desc:'A2 səviyyəsinin bütün qrammatik mövzularını (zamanlar, hallar, görünüş, modal fellər) birləşdirən yekun yazı tapşırığı və B1 səviyyəsinə keçid testi.',words:['Итог A2 — A2 yekunu','Переход на уровень B1 — B1 səviyyəsinə keçid'],hw:['10-12 cümləlik sərbəst mətn yazın: "Mənim son səyahətim" mövzusunda, ən azı 2 zaman və 3 fərqli hal işlədərək.','Bütün A2 mövzularının siyahısını yenidən nəzərdən keçirin.'],
 quiz:[{q:'A2 səviyyəsində neçə hal öyrənildi (yeni)?',o:['1','3','6'],a:1},{q:'A2-dən sonra hansı səviyyəyə keçilir?',o:['A1','B1','B2'],a:1}]}
]},
{id:'b1',name:'B1 — Orta (CEFR)',lessons:[
 {id:'b1-1',emoji:'🎭',title:'Şərt forması: сослагательное наклонение',meta:'Условное наклонение · CEFR B1.1',desc:'Şərt forması «бы» hissəciyi ilə düzəlir və fe\'lin keçmiş zaman forması ilə işlənir: Если бы я знал... (Əgər bilsəydim...), Я бы поехал (Mən gedərdim). Bu forma real olmayan və ya arzu edilən vəziyyəti bildirir.',words:['Если бы... — Əgər... olsaydı','Я бы поехал — Mən gedərdim','Я хотел бы — İstərdim ki','Было бы хорошо — Yaxşı olardı'],hw:['"Если бы я был..." ilə 3 xəyali cümlə qurun.','"Я бы хотел..." ilə öz arzularınızı yazın.'],
 quiz:[{q:'Şərt forması hansı hissəciklə düzəlir?',o:['Ли','Бы','Же'],a:1},{q:'"Если бы я знал..." nəyi bildirir?',o:['Real faktı','Real olmayan/arzu edilən vəziyyəti','Keçmiş hərəkəti'],a:1}]},
 {id:'b1-2',emoji:'🗨️',title:'Dolayı nitq',meta:'Косвенная речь · CEFR B1.1',desc:'Birbaşa nitqdən dolayı nitqə keçid: Он сказал: «Я приду» → Он сказал, что придёт (O dedi ki, gələcək). «Что» sual olmayan cümlələrdə, «ли» isə hə/yox suallarını dolayı çevirməkdə işlənir.',words:['Он сказал, что... — O dedi ki...','Она спросила, придёт ли он — O soruşdu görəsən o gələcək','Прямая речь — Birbaşa nitq','Косвенная речь — Dolayı nitq'],hw:['3 birbaşa cümləni dolayı nitqə çevirin.','"Она спросила, ли..." quruluşu ilə 2 cümlə qurun.'],
 quiz:[{q:'Sual cümləsini dolayı nitqə çevirərkən hansı söz işlənir?',o:['Что','Ли','Как'],a:1},{q:'"Он сказал, что придёт" — bu hansı nitqdir?',o:['Birbaşa','Dolayı'],a:1}]},
 {id:'b1-3',emoji:'🚶',title:'Hərəkət felləri: идти/ходить, ехать/ездить',meta:'Глаголы движения · CEFR B1.2',desc:'Rus dilinin ən çətin mövzularından biri: bir istiqamətli (идти, ехать — konkret bir dəfəlik hərəkət) və çox istiqamətli (ходить, ездить — təkrarlanan/rəftli hərəkət) fellər fərqlənir: Я иду в школу (indi məktəbə gedirəm) vs Я хожу в школу (hər gün məktəbə gedirəm).',words:['Идти — getmək (bir dəfə, piyada)','Ходить — getmək (təkrar, piyada)','Ехать — getmək (bir dəfə, nəqliyyatla)','Ездить — getmək (təkrar, nəqliyyatla)'],hw:['4 felin fərqini nümunə cümlələrlə göstərin.','"Я хожу в..." ilə öz vərdişinizi yazın.'],
 quiz:[{q:'"Ходить" hansı hərəkəti bildirir?',o:['Bir dəfəlik','Təkrarlanan','Gələcək'],a:1},{q:'"Я иду в школу" nə deməkdir?',o:['Hər gün məktəbə gedirəm','İndi məktəbə gedirəm','Məktəbə gedəcəyəm'],a:1}]},
 {id:'b1-4',emoji:'📄',title:'Feili sifət: причастие',meta:'Причастие · CEFR B1.2',desc:'Причастие fe\'l+sifət xüsusiyyətlərini birləşdirir: читающий (oxuyan — fəal, indiki), прочитавший (oxumuş — fəal, keçmiş), прочитанный (oxunmuş — passiv). Yazılı və rəsmi dildə çox işlənir.',words:['Читающий человек — oxuyan insan','Написанное письмо — yazılmış məktub','Работающий — işləyən','Сделанный — edilmiş'],hw:['3 fe\'ldən причастие düzəldin (oxumaq, yazmaq, etmək).','Причастие ilə 2 cümlə qurun.'],
 quiz:[{q:'"Читающий" hansı formadır?',o:['Fəal, indiki причастие','Passiv причастие','Fe\'l'],a:0},{q:'"Написанное письмо" nə deməkdir?',o:['Yazılacaq məktub','Yazılmış məktub','Yazan məktub'],a:1}]},
 {id:'b1-5',emoji:'🔗',title:'Feili bağlama: деепричастие',meta:'Деепричастие · CEFR B1.2',desc:'Деепричастие əlavə hərəkəti bildirir və mübtədası əsas fe\'llə eynidir: Читая книгу, он улыбался (Kitabı oxuyarkən, o gülümsəyirdi). Bu, iki hərəkəti bir cümlədə birləşdirməyə imkan verir.',words:['Читая — oxuyarkən','Сделав — edərkən/edib','Идя по улице — küçədə gedərkən','Улыбаясь — gülümsəyərək'],hw:['3 деепричастие ilə cümlə qurun.','"Читая..." ilə başlayan 2 cümlə yazın.'],
 quiz:[{q:'Деепричастие nəyi bildirir?',o:['Əlavə hərəkəti','Yalnız zamanı','Yalnız yeri'],a:0},{q:'"Читая книгу, он улыбался" — iki hərəkət eyni mübtədaya aiddirmi?',o:['Bəli','Xeyr'],a:0}]},
 {id:'b1-6',emoji:'🧵',title:'Mürəkkəb cümlələr: который, чтобы, если',meta:'Сложноподчинённые предложения · CEFR B1.3',desc:'Tabeli mürəkkəb cümlələr bağlayıcılarla qurulur: который (hansı ki — təyin budaq cümləsi), чтобы (üçün ki — məqsəd), если (əgər — şərt). Bu mövzu real danışıqda ideyaları əlaqələndirmək üçün əsasdır.',words:['Который — hansı ki','Человек, который работает — işləyən insan','Чтобы — üçün ki (məqsəd)','Если — əgər'],hw:['"Который" ilə 2 təyin budaq cümləsi qurun.','"Чтобы" ilə məqsəd bildirən 2 cümlə yazın.'],
 quiz:[{q:'"Который" hansı funksiyanı daşıyır?',o:['Təyin budaq cümləsi','Zaman budaq cümləsi','Səbəb budaq cümləsi'],a:0},{q:'"Чтобы" nəyi bildirir?',o:['Şərti','Məqsədi','Zamanı'],a:1}]},
 {id:'b1-7',emoji:'💡',title:'Fikir bildirmək',meta:'Выражение мнения · CEFR B1.3',desc:'Öz fikrini əsaslandırmaq üçün ifadələr: я думаю, что... (mən düşünürəm ki...), по-моему (mənə görə), мне кажется (mənə elə gəlir ki), я согласен/не согласен (razıyam/razı deyiləm).',words:['Я думаю, что... — Mən düşünürəm ki...','По-моему — Mənə görə','Мне кажется — Mənə elə gəlir','Я согласен / не согласен — Razıyam / razı deyiləm'],hw:['Bir mövzu haqqında öz fikrinizi 4 fərqli ifadə ilə yazın.','Razı olmadığınız bir fikri əsaslandırıb yazın.'],
 quiz:[{q:'"Мне кажется" nə deməkdir?',o:['Mən əminəm','Mənə elə gəlir','Mən bilmirəm'],a:1},{q:'"По-моему" hansı mənanı verir?',o:['Sənə görə','Mənə görə','Ona görə'],a:1}]},
 {id:'b1-8',emoji:'📧',title:'Rəsmi yazışma',meta:'Деловая переписка · CEFR B1.3',desc:'Rəsmi e-poçt/məktub strukturu: müraciət (Уважаемый...), məqsəd bildirmək (Пишу вам по поводу...), nəzakətli sonluq (С уважением). Bu, iş və təhsil mühitində vacib bir bacarıqdır.',words:['Уважаемый... — Hörmətli...','Пишу вам по поводу... — Sizə ... münasibətilə yazıram','Прошу вас... — Sizdən xahiş edirəm...','С уважением — Hörmətlə'],hw:['Qısa rəsmi e-poçt yazın (5-6 cümlə, iş müraciəti).','Rəsmi və qeyri-rəsmi salamlaşmanı müqayisə edin.'],
 quiz:[{q:'"С уважением" hansı hissədə işlənir?',o:['Başlanğıcda','Sonda','Ortada'],a:1},{q:'"Прошу вас..." nə deməkdir?',o:['Təşəkkür edirəm','Sizdən xahiş edirəm','Üzr istəyirəm'],a:1}]},
 {id:'b1-9',emoji:'📰',title:'Xəbər və mədəniyyət müzakirəsi',meta:'Обсуждение новостей и культуры · CEFR B1.4',desc:'Orta çətinlikli mətn oxuma (xəbər/məqalə üslubunda) və məzmunu müzakirə etmək bacarığı: əsas fikri tapmaq, öz sözləri ilə ümumiləşdirmək, sual-cavab.',words:['Статья — Məqalə','Новости — Xəbərlər','Автор пишет, что... — Müəllif yazır ki...','Основная идея — Əsas fikir'],hw:['Kiçik bir rusca mətn (5-6 cümlə) tapıb əsas fikrini azərbaycanca yazın.','Mətnə 3 sual tərtib edin.'],
 quiz:[{q:'"Основная идея" nə deməkdir?',o:['Son cümlə','Əsas fikir','Müəllifin adı'],a:1},{q:'Mətn üzərində işləyərkən ilk addım nədir?',o:['Əzbərləmək','Əsas fikri tapmaq','Tərcümə etmək'],a:1}]},
 {id:'b1-10',emoji:'❓',title:'Dolayı suallar',meta:'Косвенные вопросы · CEFR B1.4',desc:'Nəzakətli və dolayı sual vermək forması: Вы не могли бы сказать, где...? (Deyə bilməzsinizmi, harada...?) — birbaşa sualdan daha nəzakətlidir və rəsmi kontekstdə üstünlük təşkil edir.',words:['Вы не могли бы сказать...? — Deyə bilməzsinizmi...?','Я хотел бы узнать... — Bilmək istərdim ki...','Не подскажете...? — Deyə bilməzsinizmi...?'],hw:['3 birbaşa sualı dolayı/nəzakətli formaya çevirin.','Rəsmi kontekstdə (bank, ofis) 2 dolayı sual yazın.'],
 quiz:[{q:'Dolayı sual forması hansı kontekstdə üstünlük təşkil edir?',o:['Dostlar arasında','Rəsmi kontekstdə','Ailədə'],a:1},{q:'"Не подскажете...?" nə mənadadır?',o:['Əmr','Nəzakətli sual','Etiraz'],a:1}]},
 {id:'b1-11',emoji:'🎯',title:'Sinonimlər və üslub',meta:'Синонимы и стиль речи · CEFR B1.4',desc:'Eyni fikri fərqli üslubda (neytral/rəsmi/danışıq) ifadə etmək bacarığı: помочь (neytral) — оказать помощь (rəsmi) — подсобить (danışıq). Bu, dilin çevik istifadəsi üçün vacibdir.',words:['Помочь — kömək etmək (neytral)','Оказать помощь — kömək göstərmək (rəsmi)','Большой / огромный — böyük / nəhəng (sinonim)','Красивый / прекрасный — gözəl / gözəl (üslub fərqi)'],hw:['5 söz cütü üçün sinonim tapın.','Bir cümləni 3 fərqli üslubda (neytral/rəsmi/danışıq) yazın.'],
 quiz:[{q:'"Оказать помощь" hansı üslubdadır?',o:['Danışıq','Rəsmi','Uşaq dili'],a:1},{q:'Sinonimlərdən istifadə nəyə kömək edir?',o:['Qrammatikanı sadələşdirməyə','Dilin çevik istifadəsinə','Heç nəyə'],a:1}]},
 {id:'b1-12',emoji:'🏆',title:'B1 Yekun: Esse və keçid testi',meta:'Итоговый тест B1 · CEFR B1 → B2',desc:'B1 səviyyəsinin bütün mövzularını (şərt forması, dolayı nitq, hərəkət felləri, причастие/деепричастие, mürəkkəb cümlələr) birləşdirən yekun esse yazısı və B2 səviyyəsinə keçid testi.',words:['Итог B1 — B1 yekunu','Переход на уровень B2 — B2 səviyyəsinə keçid','Эссе — Esse'],hw:['12-15 cümləlik esse yazın: "Rusiyaya səyahət etsəydim..." mövzusunda, şərt forması, причастие və mürəkkəb cümlə işlədərək.','B1 mövzularının siyahısını təkrar nəzərdən keçirin.'],
 quiz:[{q:'B1 səviyyəsində причастие və деепричастие ilə tanış olduq. Bunlar nədir?',o:['Yalnız isimlər','Fe\'ldən düzələn xüsusi formalar','Yalnız sifətlər'],a:1},{q:'B1-dən sonra hansı səviyyəyə keçilir?',o:['A2','B2','C1'],a:1}]}
]},
{id:'b2',name:'B2 — Yuxarı Orta (CEFR)',lessons:[
 {id:'b2-1',emoji:'🔄',title:'Пассивный залог',meta:'Passiv növ · CEFR B2.1',desc:'Passiv növ hərəkətin subyektini deyil, obyektini önə çıxarır. İki yolla düzəlir: -ся şəkilçisi ilə (Дом строится рабочими — Ev fəhlələr tərəfindən tikilir) və qısa причастие ilə (Дом построен — Ev tikilib). Rəsmi və elmi mətnlərdə çox işlənir.',words:['Строится — tikilir (proses)','Построен — tikilib (nəticə)','Дом строится рабочими — Ev fəhlələr tərəfindən tikilir','Кем? — Kim tərəfindən?'],hw:['3 aktiv cümləni passivə çevirin.','-ся və qısa причастие formaları arasındakı fərqi izah edin.'],
 quiz:[{q:'"Дом построен" hansı formadır?',o:['Aktiv','Passiv (nəticə)','Passiv (proses)'],a:1},{q:'Passiv növ nəyi önə çıxarır?',o:['Subyekti','Obyekti','Zamanı'],a:1}]},
 {id:'b2-2',emoji:'📚',title:'Frazeoloji ifadələr və idiomlar',meta:'Фразеологизмы · CEFR B2.1',desc:'Rus dilində geniş yayılmış idiomatik ifadələr, hərfi mənadan fərqli məna daşıyır: бить баклуши (boş oturmaq, hərfi: "taxta parçalarını döymək"), водить за нос (aldatmaq, hərfi: "burnundan aparmaq").',words:['Бить баклуши — boş-boşuna vaxt keçirmək','Водить за нос — aldatmaq','Как две капли воды — bir-birinə çox oxşamaq','Взять себя в руки — özünü ələ almaq'],hw:['4 idiomu öz cümlələrinizdə işlədin.','2 yeni idiom tapıb mənasını izah edin.'],
 quiz:[{q:'"Водить за нос" nə deməkdir?',o:['Kömək etmək','Aldatmaq','Salamlaşmaq'],a:1},{q:'"Взять себя в руки" hərfi tərcümədən fərqli olaraq nə deməkdir?',o:['Əl tutmaq','Özünü ələ almaq','Kömək istəmək'],a:1}]},
 {id:'b2-3',emoji:'⚖️',title:'Arqumentasiya və müzakirə',meta:'Аргументация и дискуссия · CEFR B2.2',desc:'Fikri əsaslandırmaq və müzakirədə iştirak etmək üçün struktur: с одной стороны... с другой стороны (bir tərəfdən... digər tərəfdən), во-первых/во-вторых (birincisi/ikincisi), таким образом (beləliklə, nəticə).',words:['С одной стороны... — Bir tərəfdən...','С другой стороны... — Digər tərəfdən...','Во-первых, во-вторых — Birincisi, ikincisi','Таким образом — Beləliklə'],hw:['Mübahisəli bir mövzuda (məs. onlayn təhsil) "с одной стороны/с другой стороны" strukturu ilə paraqraf yazın.','3 arqument sözünü müxtəlif cümlələrdə işlədin.'],
 quiz:[{q:'"Таким образом" hansı funksiyanı daşıyır?',o:['Əks fikir bildirmək','Nəticə çıxarmaq','Sual vermək'],a:1},{q:'"С одной стороны... с другой стороны" nə üçün işlənir?',o:['İki fərqli baxışı müqayisə etmək','Zaman bildirmək','Yer bildirmək'],a:0}]},
 {id:'b2-4',emoji:'📝',title:'Rəsmi ərizə və CV',meta:'Заявление и резюме · CEFR B2.2',desc:'Rəsmi sənəd yazma bacarığı: заявление (ərizə) strukturu — başlıq, məzmun, tarix, imza; резюме (CV) üçün əsas bölmələr — опыт работы (iş təcrübəsi), образование (təhsil), навыки (bacarıqlar).',words:['Заявление — Ərizə','Прошу принять меня на работу — İşə qəbul etməyinizi xahiş edirəm','Опыт работы — İş təcrübəsi','Навыки — Bacarıqlar'],hw:['Qısa iş ərizəsi yazın (rəsmi struktur ilə).','Öz CV-nizin əsas bölmələrini rusca tərtib edin.'],
 quiz:[{q:'"Опыт работы" nə deməkdir?',o:['Təhsil','İş təcrübəsi','Bacarıqlar'],a:1},{q:'Rəsmi ərizədə hansı element mütləq olmalıdır?',o:['Zarafat','Tarix və imza','Şeir'],a:1}]},
 {id:'b2-5',emoji:'🎭',title:'Danışıq və kitab leksikası',meta:'Разговорная и книжная лексика · CEFR B2.3',desc:'Rus dilində iki əsas leksik registr var: разговорный (danışıq — классный, крутой) və книжный (kitab/rəsmi — превосходный, выдающийся). Konteksti düzgün seçmək natural nitq üçün vacibdir.',words:['Классный / крутой (разг.) — əla (danışıq)','Превосходный (книжн.) — əla (rəsmi)','Тачка (разг.) — maşın (danışıq)','Транспортное средство (книжн.) — nəqliyyat vasitəsi (rəsmi)'],hw:['5 söz cütünü (danışıq/kitab) tapıb müqayisə edin.','Bir mətni əvvəl rəsmi, sonra danışıq üslubunda yazın.'],
 quiz:[{q:'"Крутой" hansı registrə aiddir?',o:['Kitab','Danışıq','Elmi'],a:1},{q:'Rəsmi sənəddə hansı leksika işlədilməlidir?',o:['Danışıq','Kitab/rəsmi','Uşaq dili'],a:1}]},
 {id:'b2-6',emoji:'😏',title:'Modal hissəciklər: же, ведь, вот',meta:'Модальные частицы · CEFR B2.3',desc:'Kiçik hissəciklər cümləyə emosional çalar qatır: же (vurğu/təkid — Я же говорил! — Mən axı demişdim!), ведь (izah/xatırlatma — Ведь ты знаешь — Axı sən bilirsən), вот (göstərmə/vurğu — Вот это да! — Bax bu başqa!).',words:['Же — axı (vurğu)','Ведь — axı (izah)','Вот — bax, budur','Я же говорил! — Mən axı demişdim!'],hw:['3 hissəciklə emosional cümlə qurun.','Hissəciksiz və hissəcikli eyni cümləni müqayisə edin.'],
 quiz:[{q:'"Же" hissəciyi cümləyə nə əlavə edir?',o:['Sual mənası','Vurğu/təkid','Keçmiş zaman'],a:1},{q:'"Вот это да!" hansı emosiyanı bildirir?',o:['Təəccüb/heyranlıq','Kədər','Laqeydlik'],a:0}]},
 {id:'b2-7',emoji:'🔀',title:'Səbəb-nəticə əlaqələri',meta:'Причинно-следственные связи · CEFR B2.4',desc:'Mürəkkəb səbəb-nəticə cümlələri: благодаря (sayəsində — müsbət səbəb), из-за (ucbatından — mənfi səbəb), в результате (nəticədə), поэтому (buna görə də).',words:['Благодаря — sayəsində (müsbət)','Из-за — ucbatından (mənfi)','В результате — nəticədə','Поэтому — buna görə də'],hw:['"Благодаря" və "из-за" ilə fərqli mənalı 4 cümlə qurun.','Bir hadisəni səbəb-nəticə zənciri kimi 3 cümlədə izah edin.'],
 quiz:[{q:'"Благодаря" hansı mənada işlənir?',o:['Mənfi səbəb','Müsbət səbəb','Zaman'],a:1},{q:'"Из-за дождя мы остались дома" — səbəb neytraldır, yoxsa mənfi?',o:['Neytral','Mənfi','Müsbət'],a:1}]},
 {id:'b2-8',emoji:'📖',title:'Bədii mətn təhlili',meta:'Анализ художественного текста · CEFR B2.4',desc:'Qısa bədii parça (nəsr) oxuyub təhlil etmək: personajları, mövzunu, müəllifin mövqeyini müəyyən etmək. Bu, B2 səviyyəsində oxu-anlama bacarığının zirvəsidir.',words:['Персонаж — Personaj','Сюжет — Süjet','Авторская позиция — Müəllifin mövqeyi','Художественный образ — Bədii obraz'],hw:['Qısa rus bədii mətni (5-8 cümlə) tapıb oxuyun və personajları təsvir edin.','Mətnin əsas ideyasını 3 cümlədə ümumiləşdirin.'],
 quiz:[{q:'"Авторская позиция" nə deməkdir?',o:['Müəllifin adı','Müəllifin mövqeyi','Kitabın adı'],a:1},{q:'Bədii mətn təhlilində nəyə diqqət yetirilir?',o:['Yalnız qrammatika','Personaj, süjet, ideya','Yalnız orfoqrafiya'],a:1}]},
 {id:'b2-9',emoji:'🤝',title:'İş danışıqları',meta:'Деловые переговоры · CEFR B2.4',desc:'Rəsmi iş danışıqlarında işlənən struktur ifadələr: təklif vermək (позвольте предложить), razılaşmamaq (боюсь, я не могу согласиться), kompromis təklif etmək (давайте найдём компромисс).',words:['Позвольте предложить... — İcazə verin təklif edim...','Боюсь, я не могу согласиться — Təəssüf ki, razılaşa bilmirəm','Давайте найдём компромисс — Gəlin kompromis tapaq','Это выгодно для обеих сторон — Bu hər iki tərəf üçün sərfəlidir'],hw:['Qısa iş danışığı dialoqu yazın (8-10 replika, təklif+etiraz+kompromis).','4 rəsmi danışıq ifadəsini əzbərləyin.'],
 quiz:[{q:'"Боюсь, я не могу согласиться" hansı funksiyanı daşıyır?',o:['Razılıq bildirmək','Nəzakətlə etiraz etmək','Sual vermək'],a:1},{q:'"Компромисс" nə deməkdir?',o:['Qələbə','Kompromis, güzəşt','İtki'],a:1}]},
 {id:'b2-10',emoji:'🌐',title:'Regionalizmlər və dil variantları',meta:'Региональные варианты языка · CEFR B2.4',desc:'Rus dilinin fərqli regionlarda və MDB ölkələrində istifadəsindəki kiçik fərqlər, eləcə də danışıq dilində tez-tez rast gəlinən qısaltmalar və jarqon sözlər haqqında ümumi məlumat.',words:['Ща (разг.) — indi (сейчас-dan)','Чё (разг.) — nə (что-dan)','Норм (разг.) — normal, yaxşı','Литературный язык — ədəbi dil'],hw:['5 danışıq qısaltmasını ədəbi formaları ilə eyniləşdirin.','Nə zaman jarqon, nə zaman ədəbi dil işlətmək lazım olduğunu izah edin.'],
 quiz:[{q:'"Ща" sözünün ədəbi forması hansıdır?',o:['Сейчас','Скоро','Уже'],a:0},{q:'Danışıq jarqonu harada işlədilməməlidir?',o:['Dostlar arasında','Rəsmi sənəddə','Sosial mediada'],a:1}]},
 {id:'b2-11',emoji:'🎤',title:'Şifahi təqdimat',meta:'Устная презентация · CEFR B2.4',desc:'Mövzu üzrə şifahi təqdimat qurmaq bacarığı: giriş (позвольте начать с...), əsas hissə (перейдём к главному), yekun (в заключение хочу сказать) strukturu ilə 2-3 dəqiqəlik məruzə hazırlamaq.',words:['Позвольте начать с... — İcazə verin başlayım...','Перейдём к главному — Əsas mövzuya keçək','В заключение — Yekunda','Спасибо за внимание — Diqqətinizə görə təşəkkür'],hw:['Sevdiyiniz mövzu haqqında 2 dəqiqəlik şifahi təqdimat planı yazın (giriş-əsas-yekun).','4 təqdimat ifadəsini əzbərləyin.'],
 quiz:[{q:'"Перейдём к главному" hansı hissədə işlənir?',o:['Girişdə','Əsas hissəyə keçiddə','Yekunda'],a:1},{q:'Şifahi təqdimatın 3 əsas hissəsi hansılardır?',o:['Giriş, əsas, yekun','Sual, cavab, təşəkkür','Ad, tarix, imza'],a:0}]},
 {id:'b2-12',emoji:'🏆',title:'B2 Yekun: Tam sərbəst danışıq və sertifikat',meta:'Итоговый тест B2 · CEFR B2 → C1',desc:'Proqramın yekun mərhələsi: B1-B2 bütün qrammatik və leksik mövzuları özündə cəmləşdirən sərbəst yazı və şifahi özünüqiymətləndirmə, C1 səviyyəsinə (sərbəst danışıq) hazırlıq tövsiyələri ilə.',words:['Итог B2 — B2 yekunu','Свободное владение — Sərbəst dil bilgisi','Уровень C1 — C1 səviyyəsi','Поздравляем с завершением программы! — Proqramı bitirdiyiniz münasibətilə təbrik edirik!'],hw:['15-20 cümləlik sərbəst esse yazın (istənilən mövzuda), ən azı 5 fərqli B1-B2 qrammatik quruluşu işlədərək.','A1-dən B2-yə qədər öyrəndiyiniz bütün mövzuların qısa xülasəsini hazırlayın.'],
 quiz:[{q:'B2 proqramı bitdikdən sonra hansı səviyyəyə hazırlıq tövsiyə olunur?',o:['A1','B1','C1'],a:2},{q:'Bütün proqram (A1-B2) neçə dərsdən ibarətdir?',o:['24','36','48'],a:2}]}
]}
];

/* =========================================================
   DIALOGUES — Dialoq Simulyasiyası (Yeniyetmə/Böyük trek)
   Hər ssenari addım-addım gedir: NPC replikası → şagird seçimi → rəy
   ========================================================= */
const DIALOGUES = [
{id:'shop',emoji:'🛒',title:'Mağazada',desc:'Mağazada alış-veriş edirsiniz. Satıcı ilə düzgün ünsiyyət qurun.',
 steps:[
  {npc:'Здравствуйте! Чем могу помочь?',choices:[
    {text:'Здравствуйте! Я хочу купить хлеб.',correct:true,feedback:'Əla! Nəzakətli və düzgün cavab — məqsədinizi aydın bildirdiniz.'},
    {text:'Дай хлеб.',correct:false,feedback:'Bu, çox kobud səslənir. Satıcıya "Вы" ilə və nəzakətlə müraciət etmək lazımdır.'},
    {text:'Пока.',correct:false,feedback:'"Pока" vidalaşma sözüdür, burada uyğun deyil.'}
  ]},
  {npc:'Конечно! Вот хлеб. Что-нибудь ещё?',choices:[
    {text:'Да, дайте, пожалуйста, молоко.',correct:true,feedback:'Düzgün! "Дайте, пожалуйста" nəzakətli xahiş formasıdır.'},
    {text:'Молоко давай быстро.',correct:false,feedback:'Kobud və tələsdirici səslənir. Nəzakətli forma daha yaxşıdır.'}
  ]},
  {npc:'Хорошо. Это будет 5 манат. Наличными или картой?',choices:[
    {text:'Картой, пожалуйста.',correct:true,feedback:'Düzgün! Ödəniş üsulunu aydın bildirdiniz.'},
    {text:'Что такое карта?',correct:false,feedback:'Kontekstə uyğun deyil — satıcı artıq ödəniş üsulunu soruşub.'}
  ]}
 ]},
{id:'restaurant',emoji:'🍽️',title:'Restoranda',desc:'Restoranda sifariş verirsiniz. Nəzakətli və aydın danışın.',
 steps:[
  {npc:'Добрый вечер! Что будете заказывать?',choices:[
    {text:'Добрый вечер! Я хотел бы борщ и чай, пожалуйста.',correct:true,feedback:'Əla! "Я хотел бы" nəzakətli istək formasıdır, restoran üçün ən uyğunudur.'},
    {text:'Дай еду.',correct:false,feedback:'Çox qeyri-müəyyən və kobud. Konkret sifariş verməli və nəzakətli olmalısınız.'}
  ]},
  {npc:'Хорошо! Что-нибудь на десерт?',choices:[
    {text:'Нет, спасибо, это всё.',correct:true,feedback:'Düzgün — nəzakətlə imtina etdiniz və sifarişi bağladınız.'},
    {text:'Да не знаю.',correct:false,feedback:'Qeyri-müəyyən cavab. Aydın "bəli/xeyr" bildirmək daha yaxşıdır.'}
  ]},
  {npc:'Приятного аппетита! Счёт принести позже?',choices:[
    {text:'Да, спасибо, попозже.',correct:true,feedback:'Əla! Nəzakətli razılıq bildirdiniz.'},
    {text:'Счёт сейчас же!',correct:false,feedback:'Çox kəskin səslənir, kontekstlə (sifariş hələ yeni gəlib) uyğun deyil.'}
  ]}
 ]},
{id:'phone',emoji:'📞',title:'Telefon danışığı',desc:'İş yerinə zəng edib görüş təyin edirsiniz.',
 steps:[
  {npc:'Алло! Компания "Старт", слушаю вас.',choices:[
    {text:'Здравствуйте! Можно попросить Анну Ивановну?',correct:true,feedback:'Düzgün! Rəsmi telefon danışığı üçün ideal başlanğıc.'},
    {text:'Алло кто это?',correct:false,feedback:'Zəng edən şəxs özünü təqdim etməli və kimi axtardığını deməlidir.'}
  ]},
  {npc:'Одну минуту, я вас соединяю.',choices:[
    {text:'Спасибо, жду.',correct:true,feedback:'Əla, nəzakətli gözləmə cavabı.'},
    {text:'Быстрее давай.',correct:false,feedback:'Kobud səslənir — rəsmi kontekstdə uyğun deyil.'}
  ]},
  {npc:'Здравствуйте, слушаю вас.',choices:[
    {text:'Здравствуйте! Я хотел бы договориться о встрече.',correct:true,feedback:'Mükəmməl! Rəsmi və aydın məqsəd bildirmə.'},
    {text:'Хочу встречу.',correct:false,feedback:'Çox qısa və kobud. Tam və nəzakətli cümlə lazımdır.'}
  ]}
 ]}
];
