services:
  - type: web
    name: an-rus-dili-backend
    runtime: node
    rootDir: backend
    buildCommand: npm install
    startCommand: node src/server.js
    plan: free
    envVars:
      - key: PORT
        value: 5000
      - key: JWT_SECRET
        generateValue: true
      - key: DB_HOST
        fromDatabase:
          name: an-rus-dili-db
          property: host
      - key: DB_NAME
        fromDatabase:
          name: an-rus-dili-db
          property: database
      - key: DB_USER
        fromDatabase:
          name: an-rus-dili-db
          property: user
      - key: DB_PASSWORD
        fromDatabase:
          name: an-rus-dili-db
          property: password
      - key: DB_PORT
        fromDatabase:
          name: an-rus-dili-db
          property: port
      - key: DB_SSL
        value: "true"
      - key: SEED_ON_START
        value: "true"
      - key: FRONTEND_URL
        value: "https://samir210-az.github.io"

databases:
  - name: an-rus-dili-db
    plan: free
